import { readRecallJsonRecord, writeRecallJsonRecord } from './store';
import { listRecallCandidates } from './candidate-service';
import { listAbilityAssets } from './asset-service';
import { listRecallUsage } from './usage-service';
import type { RecallJsonRecord } from './types';
export interface CognitionTreeNode { id: string; type: 'source'|'candidate'|'asset'|'usage'; label: string; status?: string; maturity?: string; }
export interface CognitionTreeEdge { from: string; to: string; type: 'evidence'|'promoted_to'|'used_in'; }
export interface CognitionTreeRecord extends RecallJsonRecord { nodes: CognitionTreeNode[]; edges: CognitionTreeEdge[]; updatedAt: string; }
export async function rebuildCognitionTree(userId: string): Promise<CognitionTreeRecord> { const [candidates, assets, usages] = await Promise.all([listRecallCandidates(userId), listAbilityAssets(userId), listRecallUsage(userId)]); const nodes: CognitionTreeNode[] = []; const edges: CognitionTreeEdge[] = []; const known = new Set<string>(); const add=(n:CognitionTreeNode)=>{if(!known.has(n.id)){known.add(n.id);nodes.push(n);}}; for (const candidate of candidates) { add({id:`candidate:${candidate.id}`,type:'candidate',label:candidate.summary||candidate.judgment,status:candidate.status}); for (const source of candidate.sourceRefs) { const id=`source:${source.kind}:${source.id}`; add({id,type:'source',label:source.title||`${source.kind}:${source.id}`,status:source.degraded?'degraded':undefined}); edges.push({from:id,to:`candidate:${candidate.id}`,type:'evidence'}); } } for(const asset of assets){ add({id:`asset:${asset.id}`,type:'asset',label:asset.title,status:asset.status,maturity:asset.maturity}); edges.push({from:`candidate:${asset.candidateId}`,to:`asset:${asset.id}`,type:'promoted_to'}); } for(const usage of usages){ const id=`usage:${usage.id}`; add({id,type:'usage',label:usage.taskRunId,status:usage.outcome}); edges.push({from:`asset:${usage.assetId}`,to:id,type:'used_in'}); } const tree:CognitionTreeRecord={schemaVersion:1,ownerId:userId,id:'graph',nodes,edges,updatedAt:new Date().toISOString()}; await writeRecallJsonRecord(userId,'tree','graph',tree); return tree; }
export async function readCognitionTree(userId: string): Promise<CognitionTreeRecord|undefined> { const raw=await readRecallJsonRecord(userId,'tree','graph'); return raw as CognitionTreeRecord|undefined; }
