import { describe, expect, it, vi, beforeEach } from 'vitest';

const modelMocks = vi.hoisted(() => ({
  buildRunner: vi.fn(),
  runReflection: vi.fn(),
  hasConfiguredModel: vi.fn(),
  runCliAgent: vi.fn(),
  pickBestCliForFallback: vi.fn(),
  getCliFallback: vi.fn(),
}));

// Mock the real backend deps before importing welcome-message.
vi.mock('../../../../src/main/features/auth', () => ({
  hasConfiguredModel: modelMocks.hasConfiguredModel,
}));
vi.mock('../../../../src/main/features/recall/asset-service', () => ({
  listAbilityAssets: vi.fn(async () => []),
}));
vi.mock('../../../../src/main/features/projects', () => ({
  getProject: vi.fn(async () => null),
}));
vi.mock('../../../../src/main/features/spaces', () => ({
  getSpace: vi.fn(async () => null),
}));
vi.mock('../../../../src/main/features/role_templates', () => ({
  getRoleTemplate: vi.fn(() => null),
}));
vi.mock('../../../../src/main/features/skills', () => ({
  listSkills: vi.fn(async () => []),
}));
vi.mock('../../../../src/main/features/task_continuation', () => ({
  readContinuationSnapshot: vi.fn(async () => null),
}));
vi.mock('../../../../src/main/model/core-agent/runner', () => ({
  buildRunner: modelMocks.buildRunner,
}));
vi.mock('../../../../src/main/features/local_agents/runner', () => ({
  run: modelMocks.runCliAgent,
}));
vi.mock('../../../../src/main/features/local_agents/fallback-picker', () => ({
  pickBestCliForFallback: modelMocks.pickBestCliForFallback,
}));
vi.mock('../../../../src/main/features/cli_fallback', () => ({
  getCliFallback: modelMocks.getCliFallback,
}));

import { generateWelcomeMessage } from '../../../../src/main/features/session_import/welcome-message';
import { listAbilityAssets } from '../../../../src/main/features/recall/asset-service';
import { getSpace } from '../../../../src/main/features/spaces';
import { getRoleTemplate } from '../../../../src/main/features/role_templates';
import { listSkills } from '../../../../src/main/features/skills';
import { readContinuationSnapshot } from '../../../../src/main/features/task_continuation';

describe('generateWelcomeMessage — v1.6 structured resume template', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    modelMocks.hasConfiguredModel.mockReturnValue({ configured: true });
    modelMocks.buildRunner.mockResolvedValue({
      runner: { runReflection: modelMocks.runReflection },
    });
    modelMocks.runReflection.mockResolvedValue('');
    modelMocks.runCliAgent.mockResolvedValue({ status: 'failed', error: 'not used' });
    modelMocks.pickBestCliForFallback.mockResolvedValue(null);
    modelMocks.getCliFallback.mockReturnValue('');
    vi.mocked(listAbilityAssets).mockResolvedValue([]);
    vi.mocked(getSpace).mockResolvedValue(null);
    vi.mocked(getRoleTemplate).mockReturnValue(undefined);
    vi.mocked(listSkills).mockResolvedValue([]);
    vi.mocked(readContinuationSnapshot).mockResolvedValue(null);
  });

  it('uses the single Action Plan generated by the model', async () => {
    modelMocks.runReflection.mockResolvedValueOnce('1. 补充支付失败路径的测试并验证错误提示。\n2. 不应展示这条');
    const out = await generateWelcomeMessage({
      userId: 'u1',
      conversationId: 'c1',
      sessionSummary: '完善产品方案\n已梳理范围边界',
    });

    // 第一部分：项目介绍（真实快照数据）.
    expect(out.text).toContain('**项目**');
    expect(out.text).toContain('完善产品方案');

    // 第三部分：Action Plan 来自真实模型回复，只保留一条.
    expect(out.plan).toEqual(['补充支付失败路径的测试并验证错误提示。']);
    expect(out.text).toContain('补充支付失败路径的测试并验证错误提示');
    expect(out.text).not.toContain('不应展示这条');
    expect(modelMocks.buildRunner).toHaveBeenCalledWith(expect.objectContaining({
      userId: 'u1',
      sessionId: expect.stringMatching(/^reflect-welcome-/),
    }));
    expect(modelMocks.runReflection).toHaveBeenCalledWith(expect.stringContaining('完善产品方案'));
    expect(modelMocks.runReflection).toHaveBeenCalledWith(expect.stringContaining('只输出一条中文行动计划'));
    expect(out.text).toContain('我不会在运行中静默改写正式资产');
  });

  it('reports insufficient context without calling the model', async () => {
    const out = await generateWelcomeMessage({
      userId: 'u1',
      conversationId: 'c1',
    });

    expect(out.plan).toEqual([]);
    expect(out.text).toContain('暂未生成 Action Plan：导入会话没有提供足够的上下文');
    expect(modelMocks.buildRunner).not.toHaveBeenCalled();
  });

  it('reports when the model is unavailable without inventing a plan', async () => {
    modelMocks.buildRunner.mockRejectedValueOnce(new Error('no model'));
    const out = await generateWelcomeMessage({
      userId: 'u1',
      conversationId: 'c1',
      sessionSummary: '完善产品方案',
    });

    expect(out.plan).toEqual([]);
    expect(out.text).toContain('暂未生成 Action Plan：当前模型不可用');
    expect(out.text).not.toContain('核对产品对象和术语');
  });

  it('uses a detected local Agent when no API model is configured', async () => {
    modelMocks.hasConfiguredModel.mockReturnValue({ configured: false });
    modelMocks.pickBestCliForFallback
      .mockResolvedValueOnce({
        type: 'codex',
        path: '/usr/local/bin/codex',
        version: '1.0.0',
        available: true,
        auth: { loggedIn: true, mode: 'oauth' },
      })
      .mockResolvedValueOnce(null);
    modelMocks.runCliAgent.mockResolvedValueOnce({
      runId: 'local-plan-1',
      status: 'completed',
      output: '1. 先核对导入会话中的支付失败路径，并补齐对应测试。',
    });

    const out = await generateWelcomeMessage({
      userId: 'u1',
      conversationId: 'c1',
      sessionSummary: '完善支付流程\n已完成主流程设计',
    });

    expect(out.plan).toEqual(['先核对导入会话中的支付失败路径，并补齐对应测试。']);
    expect(out.text).toContain('先核对导入会话中的支付失败路径');
    expect(modelMocks.buildRunner).not.toHaveBeenCalled();
    expect(modelMocks.pickBestCliForFallback).toHaveBeenCalledTimes(1);
    expect(modelMocks.pickBestCliForFallback.mock.calls[0][0]).toEqual(expect.objectContaining({
      prefer: undefined,
      exclude: expect.any(Set),
    }));
    expect(modelMocks.runCliAgent).toHaveBeenCalledWith(expect.objectContaining({
      uid: 'u1',
      cli: 'codex',
      agentId: 'session-import-action-plan',
      skipDispatchCheck: true,
      prompt: expect.stringContaining('完善支付流程'),
    }));
  });

  it('reports when no local Agent is detected and does not invent a plan', async () => {
    modelMocks.hasConfiguredModel.mockReturnValue({ configured: false });
    modelMocks.pickBestCliForFallback.mockResolvedValue(null);

    const out = await generateWelcomeMessage({
      userId: 'u1',
      sessionSummary: '完善支付流程',
    });

    expect(out.plan).toEqual([]);
    expect(out.text).toContain('暂未生成 Action Plan：本机没有检测到可用的 Agent');
    expect(modelMocks.buildRunner).not.toHaveBeenCalled();
    expect(modelMocks.runCliAgent).not.toHaveBeenCalled();
  });

  it('tries the next local Agent when the first one fails', async () => {
    modelMocks.hasConfiguredModel.mockReturnValue({ configured: false });
    modelMocks.pickBestCliForFallback
      .mockResolvedValueOnce({
        type: 'codex', path: '/usr/local/bin/codex', version: '1.0.0', available: true,
        auth: { loggedIn: true, mode: 'oauth' },
      })
      .mockResolvedValueOnce({
        type: 'claude', path: '/usr/local/bin/claude', version: '1.0.0', available: true,
        auth: { loggedIn: true, mode: 'oauth' },
      })
      .mockResolvedValueOnce(null);
    modelMocks.runCliAgent
      .mockResolvedValueOnce({ runId: 'failed-1', status: 'failed', error: 'login expired' })
      .mockResolvedValueOnce({ runId: 'local-plan-2', status: 'completed', output: '检查当前接口契约并运行回归测试。' });

    const out = await generateWelcomeMessage({
      userId: 'u1',
      sessionSummary: '完善接口',
    });

    expect(out.plan).toEqual(['检查当前接口契约并运行回归测试。']);
    expect(modelMocks.runCliAgent).toHaveBeenCalledTimes(2);
    expect(modelMocks.pickBestCliForFallback.mock.calls[1][0]).toEqual(expect.objectContaining({
      prefer: undefined,
      exclude: expect.any(Set),
    }));
    expect([...modelMocks.pickBestCliForFallback.mock.calls[1][0].exclude]).toEqual(['codex']);
  });

  it('reports an empty model reply separately', async () => {
    modelMocks.runReflection.mockResolvedValueOnce('');
    const out = await generateWelcomeMessage({
      userId: 'u1',
      sessionSummary: '完善产品方案',
    });

    expect(out.plan).toEqual([]);
    expect(out.text).toContain('暂未生成 Action Plan：模型未返回有效内容');
  });

  it('produces the「准备携带」strip from real confirmed assets', async () => {
    vi.mocked(listAbilityAssets).mockResolvedValueOnce([
      { id: 'a1', type: 'personal', title: '我是产品经理', statement: '偏好', status: 'active' } as any,
      { id: 'a2', type: 'skill_method', title: '方案审查', statement: '步骤', status: 'active' } as any,
    ]);
    const out = await generateWelcomeMessage({
      userId: 'u1',
      conversationId: 'c1',
      projectId: 'p1',
      sessionSummary: '',
    });

    // 第二部分：工作空间可用能力（关于我 1项 · 我的能力 1项）.
    expect(out.text).toContain('工作空间可用能力：关于我 1项 · 我的能力 1项');
    expect(out.text).toContain('只对目标任务生效');
    // 「查看依据」按钮由前端 welcome-carry 条渲染（依赖 carry 元数据）。
    expect(out.text).not.toContain('**查看依据**');
    // carry 元数据带真实来源.
    expect(out.carry.length).toBeGreaterThan(0);
    expect(out.carry.find((c) => c.kind === 'personal')?.count).toBe(1);
    expect(out.carry.find((c) => c.kind === 'ability')?.count).toBe(1);
  });

  it('uses the empty carry strip when nothing is confirmed', async () => {
    vi.mocked(listAbilityAssets).mockResolvedValueOnce([]);
    const out = await generateWelcomeMessage({ userId: 'u1', conversationId: 'c1', sessionSummary: '' });
    expect(out.text).toContain('工作空间可用能力：无');
    expect(out.carry).toEqual([]);
  });

  it('emits structured localization facts for every carry source', async () => {
    vi.mocked(listAbilityAssets).mockResolvedValueOnce([
      { id: 'p1', type: 'personal', title: '产品经理', status: 'active' } as any,
      { id: 'a1', type: 'skill_method', title: '方案审查', status: 'active' } as any,
    ]);
    vi.mocked(getSpace).mockResolvedValueOnce({
      space_id: 's1',
      name: '产品空间',
      primary_template_id: 'product-manager',
      secondary_template_ids: [],
      extra_skills: [],
      extra_agents: [],
      base_agents: [],
      created_at: '2026-08-19T00:00:00.000Z',
      updated_at: '2026-08-19T00:00:00.000Z',
    });
    vi.mocked(getRoleTemplate).mockReturnValueOnce({
      template_id: 'product-manager',
      name: '产品经理',
      description: '',
      version: '1.0.0',
      preset_groups: [],
      bundle: { skill_ids: ['skill-review'], agent_ids: [] },
    });
    vi.mocked(listSkills).mockResolvedValueOnce([
      { id: 'skill-review', name: '技术评审', version: '2.0.0' } as any,
    ]);
    vi.mocked(readContinuationSnapshot).mockResolvedValueOnce({
      goal: '完成国际化',
      stage: '测试',
      constraints: ['保持中文语义'],
      nextStep: '验证 English UI',
      sourceSummary: '处理中英文切换',
    } as any);

    const out = await generateWelcomeMessage({
      userId: 'u1',
      conversationId: 'c1',
      spaceId: 's1',
    });

    const personal = out.carry.find((item) => item.kind === 'personal');
    const ability = out.carry.find((item) => item.kind === 'ability');
    const snapshot = out.carry.find((item) => item.kind === 'snapshot');

    expect(personal?.sourceDetails).toEqual([
      { kind: 'confirmed_personal', count: 1 },
    ]);
    expect(ability?.sourceDetails).toEqual([
      { kind: 'space_template_skills', count: 1 },
      { kind: 'confirmed_ability', count: 1 },
    ]);
    expect(snapshot?.sourceDetails).toEqual([
      { kind: 'snapshot_restored' },
    ]);
    expect(ability?.items?.map((item) => item.name)).toEqual(['技术评审', '方案审查']);
  });
});
