/* Rebuild local preview JS and token/card metadata. Uses an existing esbuild installation. */
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const esbuild = require(process.env.COGSEED_ESBUILD_PATH || process.env.RAYMOND_ESBUILD_PATH || 'esbuild');
const root = path.resolve(__dirname, '..');
const read = p => fs.readFileSync(path.join(root, p), 'utf8');
const write = (p, value) => fs.writeFileSync(path.join(root, p), value);
function files(dir) {
  return fs.readdirSync(path.join(root, dir), {withFileTypes:true}).flatMap(e =>
    e.isDirectory() ? files(path.join(dir,e.name)) : [path.join(dir,e.name)]);
}
async function main() {
  // Local SVGs are the source of truth; builds never fetch icons or require a package.
  const lucide = JSON.parse(read('assets/lucide/manifest.json'));
  const icons = Object.fromEntries(Object.entries(lucide.icons).map(([alias, name]) => {
    const asset = lucide.files[name];
    const svg = read(`assets/lucide/${asset.file}`);
    if (crypto.createHash('sha256').update(svg).digest('hex') !== asset.sha256) throw new Error(`Lucide SVG checksum mismatch: ${name}`);
    const body = svg.match(/<svg\b[^>]*>([\s\S]*?)<\/svg>/);
    if (!body || !svg.includes('viewBox="0 0 24 24"')) throw new Error(`Invalid Lucide SVG: ${name}`);
    return [alias, [body[1].trim()]];
  }));
  write('components/foundation/lucide-icons.js', `/*! Lucide local SVGs. Generated by tools/build.cjs.\n${read('assets/lucide/LICENSE')}\n*/\nexport const csIcons = ${JSON.stringify(icons, null, 2)};\n`);
  const meta = JSON.parse(read('components/registry.json'));
  meta.version = JSON.parse(read('version.json')).version;
  const grouped = new Map();
  for (const c of [...meta.components, ...meta.unexposedExports]) {
    if (!grouped.has(c.sourcePath)) grouped.set(c.sourcePath, []);
    grouped.get(c.sourcePath).push(c.name);
  }
  const entry = [...grouped].map(([p,names]) => `export { ${names.join(', ')} } from './${p}';`).join('\n');
  write('index.d.ts', [...grouped].map(([p,names]) => `export { ${names.join(', ')} } from './${p.replace(/\.jsx$/, '')}';`).join('\n')+'\n');
  write('index.js', '// Generated source entry. JSX-capable tooling and React required.\n'+entry+'\n');
  const result = await esbuild.build({absWorkingDir:root,stdin:{contents:entry,resolveDir:root,loader:'jsx'},
    bundle:true,write:false,format:'iife',globalName:meta.namespace,target:'es2020',
    alias:{react:path.join(__dirname,'react-shim.cjs')},legalComments:'inline'});
  const sources = [...files('components'),...files('ui_kits')].filter(p=>p.endsWith('.jsx'));
  meta.sourceHashes = Object.fromEntries(sources.map(p=>[p,crypto.createHash('sha256').update(read(p)).digest('hex').slice(0,12)]));
  write('_ds_bundle.js',`/* @ds-bundle: ${JSON.stringify(meta)} */\n\n${result.outputFiles[0].text}`);
  for (const p of sources.filter(p=>p.startsWith('ui_kits/') || p.endsWith('.demo.jsx'))) {
    const result = await esbuild.transform(read(p),{loader:'jsx',format:'iife',target:'es2020',legalComments:'inline'});
    write(p.replace(/\.jsx$/,'.js'),'/* Generated from '+p+' by tools/build.cjs. */\n'+result.code);
  }
  // Independent task entry reuses the application shell and all page scripts.
  write('ui_kits/enterprise-app/task.html', read('ui_kits/enterprise-app/index.html')
    .replace('<title>CogSeed · UI Kit</title>', '<title>任务 · 对话详情 · CogSeed</title>')
    .replace('<div id="root"></div>', '<div id="root" data-preview-page="task"></div>')
    .replace('name="企业版桌面端"', 'name="任务 · 对话详情"'));
  write('ui_kits/enterprise-app/cognition.html', read('ui_kits/enterprise-app/index.html')
    .replace('<title>CogSeed · UI Kit</title>', '<title>认知资产 · CogSeed</title>')
    .replace('<div id="root"></div>', '<div id="root" data-preview-page="cognition"></div>')
    .replace('name="企业版桌面端"', 'name="认知资产"'));
  const manifest = JSON.parse(read('_ds_manifest.json'));
  manifest.version = JSON.parse(read('version.json')).version;
  manifest.components = meta.components;
  const oldTokens = new Map(manifest.tokens.map(t=>[t.name,t]));
  manifest.tokens = files('tokens').filter(p=>p.endsWith('.css')).flatMap(p=>
    [...read(p).matchAll(/(--cs-[\w-]+):([^;]+);/g)].map(m=>({
      name:m[1],value:m[2].trim(),kind:({'--cs-link':'color','--cs-link-hover':'color'}[m[1]]) || oldTokens.get(m[1])?.kind || 'other',definedIn:p
    })));
  manifest.cards = [...files('guidelines'),...files('components'),...files('ui_kits')].filter(p=>p.endsWith('.html')).flatMap(p=>{
    const card = read(p).match(/<!-- @dsCard ([\s\S]*?)-->/);
    if (!card) return [];
    return [{path:p,...Object.fromEntries([...card[1].matchAll(/([\w]+)="([^"]*)"/g)].map(m=>[m[1],m[2]]))}];
  });
  manifest.globalCssPaths = [...read('styles.css').matchAll(/@import url\("([^"]+)"\);/g)].map(m=>m[1]).concat('styles.css');
  manifest.fonts = [];
  manifest.brandFonts = []; // System sans-serif only; no bundled or named brand fonts.
  write('_ds_manifest.json',JSON.stringify(manifest,null,2)+'\n');
  const inventory = [...grouped].map(([source,names]) => `| [${source}](${source}) | ${names.join(' · ')} |`).join('\n');
  write('components.md', `# 组件清单\n\n由 components/registry.json 生成，请通过源注册表维护。\n\n公开组件 ${meta.components.length} 个，辅助导出 ${meta.unexposedExports.length} 个。\n\n| 源文件 | 导出 |\n| --- | --- |\n${inventory}\n`);
  const adherence = JSON.parse(read('_adherence.oxlintrc.json'));
  adherence['x-omelette'].tokens = manifest.tokens.map(t=>t.name).sort();
  adherence['x-omelette'].tokenKinds = Object.fromEntries(manifest.tokens.map(t=>[t.name,t.kind]));
  adherence['x-omelette'].fontFamilies = ['system-ui','sans-serif'];
  write('_adherence.oxlintrc.json',JSON.stringify(adherence,null,2)+'\n');
  process.stdout.write(`Built ${meta.components.length} components, ${sources.filter(p=>p.startsWith('ui_kits/') || p.endsWith('.demo.jsx')).length} preview scripts, ${manifest.cards.length} cards.\n`);
}
main().catch(e=>{process.stderr.write(e.stack+'\n');process.exitCode=1;});
