import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';

import {
  MARKETPLACE_RESOURCE_MANIFEST_NAME,
  marketplaceContentTreeFiles,
  marketplaceContentTreeHash,
  marketplaceContentTreeHashForFiles,
} from '../../../src/main/util/marketplace-tree-hash';

let tmpDir: string;

beforeEach(() => {
  tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'orkas-marketplace-tree-hash-'));
});

afterEach(() => {
  fs.rmSync(tmpDir, { recursive: true, force: true });
});

function writeFile(rel: string, content: string): void {
  const file = path.join(tmpDir, rel);
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, content, 'utf8');
}

describe('marketplaceContentTreeHash', () => {
  it('ignores Resource/dev sidecars when hashing marketplace content', () => {
    writeFile('SKILL.md', '# Body\n');
    writeFile('assets/template.txt', 'template\n');
    const before = marketplaceContentTreeHash(tmpDir);

    writeFile(MARKETPLACE_RESOURCE_MANIFEST_NAME, '{}\n');
    writeFile('assets/_install.json', '{}\n');
    writeFile('assets/_cache.json', '{}\n');
    writeFile('.DS_Store', 'local\n');
    writeFile('__pycache__/ignored.pyc', 'local\n');

    // Codepoint order: 'SKILL.md' (S=0x53) sorts before 'assets/...' (a=0x61).
    expect(marketplaceContentTreeFiles(tmpDir)).toEqual(['SKILL.md', 'assets/template.txt']);
    expect(marketplaceContentTreeHash(tmpDir)).toBe(before);
  });

  it('matches the Python-side digest for a mixed-case tree (cross-language codepoint contract)', () => {
    // Resource/sync-resource-marketplace.py computes the same sha256-tree-v1 digest
    // by codepoint-ordered posix rel paths, and the committed online-hashes.json
    // baselines are Python-produced. This value was generated by replicating the
    // Python algorithm over this exact fixture (SKILL.md vs assets/scripts is the
    // mixed-case ordering trap). If the TS sort drifts back to localeCompare, this
    // fails — dev-boot resource sync would then see every unchanged item as modified.
    writeFile('SKILL.md', '---\nname: t\n---\nbody\n');
    writeFile('assets/a.txt', 'alpha');
    writeFile('scripts/x.py', "print('x')\n");
    expect(marketplaceContentTreeHash(tmpDir))
      .toBe('ffade25358aad8fd24d9ef3a5db7779ac272869e9b32c7b68db87a63f4935b50');
  });

  it('hashes an explicit normalized file list in stable order', () => {
    writeFile('a.txt', 'a\n');
    writeFile('b.txt', 'b\n');

    expect(marketplaceContentTreeHashForFiles(tmpDir, ['b.txt', 'a.txt', 'a.txt']))
      .toBe(marketplaceContentTreeHash(tmpDir));
    expect(marketplaceContentTreeHashForFiles(tmpDir, [
      '../outside.txt',
      MARKETPLACE_RESOURCE_MANIFEST_NAME,
      'b.txt',
      'a.txt',
    ])).toBe(marketplaceContentTreeHash(tmpDir));
  });

  it('returns empty when an explicit file list points at a missing file', () => {
    writeFile('a.txt', 'a\n');

    expect(marketplaceContentTreeHashForFiles(tmpDir, ['a.txt', 'missing.txt'])).toBe('');
  });
});
