/**
 * Session store — maps a session_id (one per conversation) to a
 * `PersistentSession` backed by a JSONL file under
 * `data/<user_id>/{cloud,local}/sessions/<session_id>.jsonl`.
 *
 * session_id format (see CLAUDE.md §5):
 *   `<kind>-<tail>` — kind ∈ {gconv | gmember | skill | agent | extract-img |
 *   reflect | memory-extract | anon | cli}. The kind keyword is the FIRST
 *   segment, never an arbitrary prefix.
 *
 *   user scoping comes from path root: `<activeUid>/{cloud,local}/sessions/<sid>.jsonl`
 *   resolved via `getActiveUserId()`. The session_id intentionally does NOT
 *   carry uid — repeating it in the filename added zero security (`sessionFileFor`
 *   was self-checking the prefix it just got handed) and forced uid to be
 *   dash-free, which broke when OAuth UUIDs entered the system.
 *
 *   Builders (no uid param): features/group_chat/state.ts::{buildGconv,buildGmember}SessionId,
 *     features/agents.ts::defaultAgentEditSessionId, features/skills.ts::defaultSkillSessionId.
 *
 *   Legacy formats (`aiteam-…` brand prefix, `<uid>-<kind>-<tail>` uid prefix) are
 *   stripped once at startup by `util/migrate-session-ids.ts` and should not appear
 *   here at runtime.
 *
 * session jsonl carries the raw resumable LLM-turn history (tool_use /
 * tool_result pairs included). `Session.getMessagesForModel()` applies a
 * transient model-facing view: completed history is projected to summary +
 * bounded user/final-assistant I/O, while the active turn keeps recent tool
 * process messages. The raw JSONL remains separate from
 * `<uid>/cloud/chats/<cid>.jsonl` (the UI-facing view).
 */

import * as path from 'node:path';
import * as fs from 'node:fs';
import * as fsp from 'node:fs/promises';

import {
  sessionToolResultsDir,
  userLocalSessionFile,
} from '../../paths';
import {
  cloudSessionFileFor,
  cloudSessionToolResultsDirFor,
} from '../../util/project-layout';
import { getActiveUserId } from '../../features/users';
import { createLogger } from '../../logger';
import { logErrorRef, logPathRef, maskId } from '../../util/log-redact';

const log = createLogger('model');

/**
 * "Ephemeral" kinds — one-shot background LLM calls that nobody resumes:
 *   extract-img    — KB image understanding (single image → description)
 *   reflect        — agent metacognition / reflection
 *   memory-extract — periodic fact extraction from compaction summaries
 *   anon           — fallback when a caller of `streamChatWithModel` didn't
 *                    pass a sessionId (auto-generated by client.ts)
 *   aside          — read-only "ask aside" explanation of a main conversation
 *                    (features/conversation_aside). Ephemeral on purpose: the
 *                    user-visible thread is persisted by the feature itself in
 *                    `aside.jsonl`, so the model transcript is throwaway and
 *                    must not sync or be resumed.
 * These land under `<uid>/local/sessions/` so they:
 *   - never cross devices (sync cost = 0 for throwaway transcripts);
 *   - GC out of band via `features/sessions_sweep.ts` (mtime-based 7d).
 * Every other kind (gconv / gmember / skill / agent) is "resumable" and
 * stays in `cloud/sessions/`, life-cycled with its owning entity (cid /
 * sid / aid).
 */
const EPHEMERAL_KINDS = ['extract-img', 'reflect', 'memory-extract', 'anon', 'gworker', 'aside'] as const;

/** All recognised kind keywords (used by `resolveSessionPath`'s kind-anchor assertion).
 *  Order matters in the regex alternation: longer alternatives must come before their
 *  shorter prefix overlaps so that e.g. `extract-img-…` matches as one kind, not as
 *  `extract` + leftover. */
const KNOWN_KINDS_RE = /^(gmember|gworker|gconv|memory-extract|extract-img|reflect|skill|agent|anon|aside|cli)(?:-|$)/;

export function isEphemeralSessionId(sessionId: string): boolean {
  for (const kind of EPHEMERAL_KINDS) {
    if (sessionId === kind || sessionId.startsWith(`${kind}-`)) return true;
  }
  return false;
}

/** The kind keyword anchoring a session id (`<kind>-<tail>`), or null if it
 *  doesn't start with a known kind. Used to gate per-kind behaviour (e.g. which
 *  sessions get cross-session memory). */
export function sessionKindOf(sessionId: string): string | null {
  const m = KNOWN_KINDS_RE.exec(sessionId);
  return m ? m[1] : null;
}

/** The per-agent cross-session-memory scope id for a session, or null when the
 *  session is NOT memory-eligible. Commander (gconv) → reserved 'commander';
 *  agent workers (gmember / gworker / cli) → their agent id; authoring /
 *  ephemeral sessions (agent-edit / skill-edit / extract-img / anon / reflect /
 *  memory-extract) → null (no memory read or write). When null the runner
 *  injects no memory block and does not expose the memory tool. */
export function memoryScopeForSession(sessionId: string, agentId: string): string | null {
  const kind = sessionKindOf(sessionId);
  if (kind === 'gconv') return agentId || 'commander';
  if (kind === 'gmember' || kind === 'gworker' || kind === 'cli') return agentId || null;
  return null;
}

/**
 * Build the filesystem path that backs a given session id, picking cloud or
 * local based on the kind (see EPHEMERAL_KINDS above).
 *
 * Defensive assertion: `sessionId` must start with a known kind keyword.
 * Catches accidental hand-built ids that don't go through a builder; without
 * this guard a malformed id would just silently land at a wrong-shaped jsonl
 * filename. user scoping itself is enforced by the caller passing `userId`
 * (`sessionFileFor` reads it from `getActiveUserId()`); the session_id no
 * longer carries it.
 *
 * Constructors (chats / group_chat / agents-edit / skills-edit / kb image
 * extract / reflection / cli) must build ids via the feature-layer helpers;
 * never by hand.
 */
export function resolveSessionPath(userId: string, sessionId: string): string {
  if (!KNOWN_KINDS_RE.test(sessionId)) {
    throw new Error(
      `invalid session id "${sessionId}" — must start with a known kind ` +
      `(gconv | gmember | gworker | skill | agent | extract-img | reflect | memory-extract | anon | aside | cli)`,
    );
  }
  return isEphemeralSessionId(sessionId)
    ? userLocalSessionFile(userId, sessionId)
    : cloudSessionFileFor(userId, sessionId);
}

export function sessionFileFor(sessionId: string): string {
  return resolveSessionPath(getActiveUserId(), sessionId);
}

export function toolResultsDirForSession(userId: string, sessionId: string): string {
  // Validate the id with the same router that owns the session jsonl path.
  resolveSessionPath(userId, sessionId);
  return isEphemeralSessionId(sessionId)
    ? sessionToolResultsDir(userId, sessionId)
    : cloudSessionToolResultsDirFor(userId, sessionId);
}

/**
 * Lazy cache of loaded `PersistentSession` instances keyed by session_id.
 * Two concurrent calls with the same session_id get the same instance so
 * the in-memory history stays consistent — the per-session Mutex in
 * `util/locks.sessionLock` serializes them upstream anyway.
 */
type PersistentSessionCtor = typeof import('#core-agent').PersistentSession;
type PersistentSessionInstance = InstanceType<PersistentSessionCtor>;

const cache = new Map<string, PersistentSessionInstance>();

let _ctorPromise: Promise<PersistentSessionCtor> | null = null;
async function getCtor(): Promise<PersistentSessionCtor> {
  if (!_ctorPromise) {
    _ctorPromise = import('#core-agent').then((m) => m.PersistentSession);
  }
  return _ctorPromise;
}

/**
 * Load (or reuse a cached) PersistentSession for a session id. The
 * constructor transparently reads any prior jsonl lines into memory.
 */
export async function getSession(sessionId: string): Promise<PersistentSessionInstance> {
  const cached = cache.get(sessionId);
  if (cached) return cached;

  const userId = getActiveUserId();
  const file = resolveSessionPath(userId, sessionId);
  fs.mkdirSync(path.dirname(file), { recursive: true });

  const Ctor = await getCtor();
  const session = new Ctor({
    sessionFile: file,
  });
  cache.set(sessionId, session);
  return session;
}

export interface SessionMessageRecord {
  role: 'user' | 'assistant' | 'system';
  content: unknown[];
  turnId?: number;
}

/** Copy a durable session JSONL and its PersistentSession context sidecar.
 * Tool-result spill directories are intentionally not copied: copy/merge
 * preserve references in history, not produced-file bodies. */
export async function cloneSessionForUser(
  userId: string,
  sourceSessionId: string,
  destinationSessionId: string,
): Promise<void> {
  const source = resolveSessionPath(userId, sourceSessionId);
  const destination = resolveSessionPath(userId, destinationSessionId);
  if (source === destination) throw new Error('source and destination sessions must differ');
  await fsp.mkdir(path.dirname(destination), { recursive: true });
  if (fs.existsSync(source)) await fsp.copyFile(source, destination);
  else await fsp.writeFile(destination, '', 'utf8');
  const sourceContext = `${source}.context.json`;
  const destinationContext = `${destination}.context.json`;
  if (fs.existsSync(sourceContext)) {
    let durableContext: Record<string, unknown> | null = null;
    try {
      const parsed = JSON.parse(await fsp.readFile(sourceContext, 'utf8')) as Record<string, unknown>;
      if (parsed?.version === 1) {
        durableContext = {
          version: 1,
          nextTurnId: Number.isInteger(parsed.nextTurnId) && Number(parsed.nextTurnId) > 0
            ? Number(parsed.nextTurnId)
            : 1,
          ...(typeof parsed.historySummary === 'string' && parsed.historySummary
            ? { historySummary: parsed.historySummary }
            : {}),
          ...(Number.isInteger(parsed.summaryVersion) && Number(parsed.summaryVersion) > 0
            ? { summaryVersion: Number(parsed.summaryVersion) }
            : {}),
          ...(Number.isInteger(parsed.summaryThroughTurnId) && Number(parsed.summaryThroughTurnId) > 0
            ? { summaryThroughTurnId: Number(parsed.summaryThroughTurnId) }
            : {}),
        };
      }
    } catch (err) {
      log.warn('session context clone skipped malformed sidecar', {
        user_id: maskId(userId),
        session_id: maskId(sourceSessionId),
        error: logErrorRef(err),
      });
    }
    if (durableContext) {
      const tmp = `${destinationContext}.tmp`;
      try {
        await fsp.writeFile(tmp, `${JSON.stringify(durableContext, null, 2)}\n`, 'utf8');
        await fsp.rename(tmp, destinationContext);
      } catch (err) {
        await fsp.rm(tmp, { force: true });
        throw err;
      }
    } else {
      await fsp.rm(destinationContext, { force: true });
    }
  } else await fsp.rm(destinationContext, { force: true });
  evictSession(destinationSessionId);
}

export async function readSessionMessagesForUser(
  userId: string,
  sessionId: string,
): Promise<SessionMessageRecord[]> {
  const file = resolveSessionPath(userId, sessionId);
  if (!fs.existsSync(file)) return [];
  const lines = (await fsp.readFile(file, 'utf8')).split('\n');
  const out: SessionMessageRecord[] = [];
  for (const line of lines) {
    if (!line.trim()) continue;
    try {
      const row = JSON.parse(line) as Partial<SessionMessageRecord>;
      if ((row.role === 'user' || row.role === 'assistant' || row.role === 'system') && Array.isArray(row.content)) {
        out.push({ role: row.role, content: row.content, ...(Number.isInteger(row.turnId) ? { turnId: row.turnId } : {}) });
      }
    } catch { /* ignore malformed session lines */ }
  }
  return out;
}

export async function writeSessionMessagesForUser(
  userId: string,
  sessionId: string,
  messages: SessionMessageRecord[],
): Promise<void> {
  const file = resolveSessionPath(userId, sessionId);
  await fsp.mkdir(path.dirname(file), { recursive: true });
  const body = messages.map((message) => JSON.stringify({ ...message, ts: Date.now() })).join('\n');
  await fsp.writeFile(file, body ? `${body}\n` : '', 'utf8');
  await fsp.rm(`${file}.context.json`, { force: true });
  evictSession(sessionId);
}

/** Write a merged summary transcript together with the minimal context state
 * PersistentSession needs to resume from that summary. */
export async function writeMergedSessionSummaryForUser(
  userId: string,
  sessionId: string,
  messages: SessionMessageRecord[],
  summary: string,
): Promise<void> {
  await writeSessionMessagesForUser(userId, sessionId, messages);
  const contextFile = `${resolveSessionPath(userId, sessionId)}.context.json`;
  const tmp = `${contextFile}.tmp`;
  const context = {
    version: 1,
    nextTurnId: 1,
    historySummary: summary,
    summaryVersion: 1,
  } as const;
  await fsp.writeFile(tmp, `${JSON.stringify(context, null, 2)}\n`, 'utf8');
  await fsp.rename(tmp, contextFile);
  evictSession(sessionId);
}

/** Drop a cached session — used when the underlying conversation is deleted. */
export function evictSession(sessionId: string): void {
  cache.delete(sessionId);
}

/** Delete the on-disk jsonl. Caller is responsible for also evicting. */
export function deleteSessionFile(sessionId: string): void {
  const userId = getActiveUserId();
  const file = resolveSessionPath(userId, sessionId);
  try { fs.unlinkSync(file); }
  catch (err) {
    if ((err as NodeJS.ErrnoException).code !== 'ENOENT') {
      log.warn('session file delete failed', {
        session_id: maskId(sessionId),
        path: logPathRef(file),
        error: logErrorRef(err),
      });
    }
  }
  try { fs.unlinkSync(`${file}.context.json`); }
  catch (err) {
    if ((err as NodeJS.ErrnoException).code !== 'ENOENT') {
      log.warn('session context file delete failed', {
        session_id: maskId(sessionId),
        path: logPathRef(`${file}.context.json`),
        error: logErrorRef(err),
      });
    }
  }
  try { fs.rmSync(toolResultsDirForSession(userId, sessionId), { recursive: true, force: true }); }
  catch (err) { log.warn('session tool-results delete failed', { session_id: maskId(sessionId), error: logErrorRef(err) }); }
}

/** Same as deleteSessionFile but takes an explicit userId (caller has the
 *  uid in scope and doesn't want to depend on the global active uid — e.g.
 *  chats.deleteConversation passes ctx.userId). */
export function deleteSessionFileForUser(userId: string, sessionId: string): void {
  const file = resolveSessionPath(userId, sessionId);
  try { fs.unlinkSync(file); }
  catch (err) {
    if ((err as NodeJS.ErrnoException).code !== 'ENOENT') {
      log.warn('session file delete failed', {
        user_id: maskId(userId),
        session_id: maskId(sessionId),
        path: logPathRef(file),
        error: logErrorRef(err),
      });
    }
  }
  try { fs.unlinkSync(`${file}.context.json`); }
  catch (err) {
    if ((err as NodeJS.ErrnoException).code !== 'ENOENT') {
      log.warn('session context file delete failed', {
        user_id: maskId(userId),
        session_id: maskId(sessionId),
        path: logPathRef(`${file}.context.json`),
        error: logErrorRef(err),
      });
    }
  }
  try { fs.rmSync(toolResultsDirForSession(userId, sessionId), { recursive: true, force: true }); }
  catch (err) {
    log.warn('session tool-results delete failed', {
      user_id: maskId(userId),
      session_id: maskId(sessionId),
      error: logErrorRef(err),
    });
  }
}

/** Flush all cached sessions — called by `features/users.activateUser()` on uid switch. */
export function _evictAll(): void {
  cache.clear();
}

/** For diagnostics / tests. */
export function _cacheSize(): number {
  return cache.size;
}
