import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import * as fs from 'node:fs'; import * as os from 'node:os'; import * as path from 'node:path';
import { inspectSmokeContracts, runSmoke } from '../../scripts/smoke-p3394-real-execution.mjs';
let root=''; const uid='smoke-user';
beforeEach(()=>{root=fs.mkdtempSync(path.join(os.tmpdir(),'p3394-smoke-'));fs.writeFileSync(path.join(root,'users.json'),JSON.stringify({current_user_id:uid}));});
afterEach(()=>fs.rmSync(root,{recursive:true,force:true}));
function seed(){const base=path.join(root,uid,'local','kstar','executions');fs.mkdirSync(path.join(base,'receipt-exec'),{recursive:true});fs.mkdirSync(path.join(base,'prepared-receipt'),{recursive:true});fs.mkdirSync(path.join(base,'baseline-1'),{recursive:true});fs.mkdirSync(path.join(base,'treatment-1'),{recursive:true});fs.mkdirSync(path.join(base,'validations'),{recursive:true});fs.mkdirSync(path.join(root,uid,'cloud','sessions'),{recursive:true});fs.writeFileSync(path.join(root,uid,'cloud','sessions','gmember-real.jsonl'),'{}\n');fs.writeFileSync(path.join(base,'prepared-receipt','record.json'),JSON.stringify({executionId:'prepared-receipt',sessionId:'gmember-real',boundary:'real'}));fs.writeFileSync(path.join(base,'prepared-receipt','context-reuse-receipt.json'),JSON.stringify({status:'prepared'}));for(const [id,record] of [['receipt-exec',{executionId:idFor('receipt-exec'),sessionId:'gmember-real',boundary:'real'}],['baseline-1',{executionId:'baseline-1',sessionId:'gmember-real',boundary:'real',resultRef:'output:one'}],['treatment-1',{executionId:'treatment-1',sessionId:'gmember-real',boundary:'real',artifactIds:['a1']}]] as any){fs.writeFileSync(path.join(base,id,'record.json'),JSON.stringify(record));}fs.writeFileSync(path.join(base,'receipt-exec','context-reuse-receipt.json'),JSON.stringify({status:'completed'}));fs.writeFileSync(path.join(base,'validations','validation-1.json'),JSON.stringify({status:'pass'}));}
function idFor(x:string){return x;}
describe('p3394 smoke contract',()=>{it('reports named missing prerequisites without mutating data',()=>{const before=fs.readdirSync(root);const out=inspectSmokeContracts(root,uid);expect(out.ok).toBe(false);expect(out.missing).toContain('baseline_execution');expect(fs.readdirSync(root)).toEqual(before);});it('passes a fully seeded acceptance contract',()=>{seed();const out=runSmoke({root,uid});expect(out.ok).toBe(true);expect(out.summary).toMatchObject({baseline:true,treatment:true,completedReceipt:true,validations:1});});});
