// Skills capability composition. Reference: renderer/modules/skills.js, renderSkillsGrid,
// _openSkillsSectionHtml, _openSkillRowMenu, openSkillModal. No IPC or installed data.
// Security receipts are fixture evidence, never generated by a simulated scanner.
// Imported URLs/folders are not fetched or installed; the import form retains input
// and reports the unavailable transport. Local authoring only changes React state.
(function () {
  const {ResourceCard,CardGrid,GroupHeading,Input,Textarea,Field,Tabs,SegmentedControl,Button,DropdownMenu,Dialog,StatusDot,EmptyState} = window.CogSeedDesignSystem_f581b5;
  const sources={custom:'自定义',platform:'平台',external:'外部包',global:'全局文件夹'};
  const initial=[
    {id:'credit-check',name:'项目报告口径核验',source:'custom',category:'数据分析',description:'核对报表期间、币种与合并范围，列出差异和需要补充的依据。',enabled:true,security:'通过',body:'# 项目报告口径核验\n\n读取本次任务提供的财务材料，逐项比对期间、币种与合并范围。\n\n交付：差异清单、来源页码、待核实事项。'},
    {id:'material-list',name:'调研材料清单',source:'custom',category:'文档处理',description:'按项目材料清单检查缺失项，形成补件清单。',enabled:true,security:'待检查',body:'# 调研材料清单\n\n逐项核验已提供的材料。缺少证据时记录待补充，不推断审核结论。'},
    {id:'document-summary',name:'文档摘要',source:'platform',category:'文档处理',description:'提取长文档的核心结论、关键数字与引用位置。',enabled:true,security:'通过',body:'# 文档摘要\n\n先明确摘要用途，再提取核心结论和证据位置。'},
    {id:'table-review',name:'表格核对',source:'platform',category:'数据分析',description:'核对汇总口径、异常数值和明细之间的对应关系。',enabled:true,security:'阻止使用',body:'# 表格核对\n\n此版本的执行脚本需要重新检查。'},
    {id:'office-tools',name:'办公文档工具包',source:'external',category:'文档处理',description:'提供文档格式转换与表格整理工具。',enabled:true,security:null,version:'1.2.0',body:'文档转换\n表格整理'},
    {id:'report-outline',name:'report-outline',source:'global',category:'文档处理',description:'根据材料生成分层报告提纲。',enabled:true,security:null,body:'# 报告提纲\n\n按结论、证据、待确认事项组织报告。'},
    {id:'report-review',name:'report-review',source:'global',category:'文档处理',description:'检查报告结构与引用是否完整。',enabled:false,security:null,body:'# 报告复核\n\n检查章节结构和证据引用。'}
  ];
  let previewItems=initial;
  const stack={display:'grid',gap:'var(--cs-space-4)'};
  function CapabilitySkills({onUse}) {
    const [items,setItems]=React.useState(()=>previewItems),[query,setQuery]=React.useState(()=>new URLSearchParams(location.search).get('query')||''),[category,setCategory]=React.useState('全部');
    const readRoute=()=>new URLSearchParams(location.search).get('skill');
    const [selected,setSelected]=React.useState(readRoute),[view,setView]=React.useState('content'),[expanded,setExpanded]=React.useState(false);
    const [modal,setModal]=React.useState(null),[method,setMethod]=React.useState(0),[draft,setDraft]=React.useState({name:'',description:'',url:''}),[error,setError]=React.useState(''),[notice,setNotice]=React.useState(''),[text,setText]=React.useState('');
    React.useEffect(()=>{const restore=()=>{setSelected(readRoute());setQuery(new URLSearchParams(location.search).get('query')||'');setView('content');setModal(null);};window.addEventListener('popstate',restore);return()=>window.removeEventListener('popstate',restore);},[]);
    React.useEffect(()=>{previewItems=items;},[items]);
    const open=(id,next='content')=>{const url=new URL(location.href);if(id)url.searchParams.set('skill',id);else url.searchParams.delete('skill');history.pushState(null,'',url);setSelected(id);setView(next);setNotice('');};
    const patch=(id,change)=>setItems(old=>old.map(item=>item.id===id?{...item,...change}:item));
    const inMarket=selected==='market'||selected?.startsWith('market:');
    const current=items.find(item=>item.id===selected);
    const use=item=>onUse?.({title:`使用${item.name}开展工作`,content:'empty',initialMessage:`使用技能「${item.name}」：`,skill:{id:item.id,name:item.name,source:item.source}});
    const showCreate=()=>{setDraft({name:'',description:'',url:''});setMethod(0);setError('');setModal({kind:'create'});};
    const matching=item=>(!query.trim()||`${item.name} ${item.description}`.toLowerCase().includes(query.trim().toLowerCase()))&&(category==='全部'||item.category===category);
    const visible=items.filter(matching);
    const trusted=items.filter(item=>item.source==='custom'||item.source==='platform');
    const count=status=>trusted.filter(item=>item.security===status).length;
    const security=item=><StatusDot tone={item.security==='通过'?'success':item.security==='阻止使用'?'critical':'attention'} label={`安检${item.security}`} />;
    const menu=item=>({groups:[{items:[{label:'查看详情',onSelect:()=>open(item.id)},...(item.source==='custom'?[{label:'编辑技能',onSelect:()=>{open(item.id,'edit');setText(item.body);}}]:[]),{label:item.enabled?'停用':'启用',onSelect:()=>patch(item.id,{enabled:!item.enabled})}]},...(item.source==='custom'?[{danger:true,items:[{label:'删除技能',onSelect:()=>setModal({kind:'delete',item})}]}]:[])]});
    const card=item=><ResourceCard key={item.id} variant="capability" title={item.name} icon="fileText" description={item.description} status={<StatusDot tone={item.enabled?'success':'idle'} label={item.enabled?item.category:'已停用'} />} action={item.source==='external'?'查看工具包':'使用'} disabled={item.source!=='external'&&(!item.enabled||item.security==='阻止使用')} onAction={()=>item.source==='external'?open(item.id):use(item)} menu={menu(item)}>{item.security&&<Button variant="ghost" onClick={()=>open(item.id,'security')}>{security(item)}</Button>}{item.source==='external'&&<span>{item.version} · 2 项技能</span>}</ResourceCard>;
    const saveCreate=()=>{
      if(method!==0){setError(method===1?'尚未连接导入服务，地址已保留。':'文件夹导入暂不可用，请稍后重试。');return;}
      const name=draft.name.trim();if(!name||name.length>60){setError('技能名称须为 1–60 个字符。');return;}
      if(!draft.description.trim()){setError('请填写技能要完成的工作。');return;}
      if(items.some(item=>item.source==='custom'&&item.name===name)){setError('已存在同名自定义技能，请修改名称。');return;}
      const id=`custom-${Date.now()}`;
      setItems(old=>[...old,{id,name,description:draft.description.trim(),source:'custom',category:'通用',enabled:true,security:'待检查',body:`# ${name}\n\n${draft.description.trim()}`}]);setModal(null);setQuery('');setCategory('全部');open(id);setNotice('技能已创建，可继续编辑使用说明。');
    };
    return <div className="cs-skills-layout" style={stack}>
      {notice&&<p role="status" className="cs-resource-page-notice">{notice}</p>}
      {inMarket?<window.CapabilityMarketplace kind="skill" selectedId={selected.startsWith('market:')?selected.slice(7):null} onSelect={id=>open(id?`market:${id}`:'market')} onBack={()=>open(null)}/>:selected ? current ? <>
        <div className="cs-resource-page-toolbar"><Button onClick={()=>open(null)}>返回技能</Button><h2 style={{font:'var(--cs-type-title)',margin:0}}>{current.name}</h2><span style={{flex:1}}/><DropdownMenu trigger={<Button>更多操作</Button>} {...menu(current)}/>{current.source!=='external'&&<Button disabled={!current.enabled||current.security==='阻止使用'} onClick={()=>use(current)}>使用</Button>}</div>
        <p>{sources[current.source]} · {current.category}{current.version?` · ${current.version}`:''}</p>
        <Tabs items={['使用说明',...(current.security?['安检详情']:[])]} value={view==='security'?1:0} onChange={index=>setView(index?'security':'content')}/>
        {view==='security'?<section style={stack} aria-label="技能安检详情">{security(current)}<p>{current.security==='通过'?'最近记录未发现阻断项。':current.security==='阻止使用'?'执行脚本包含未批准的外部调用，本版本暂不可使用。':'当前内容尚无检查结果。'}</p><dl><dt>检查范围</dt><dd>SKILL.md、执行脚本与依赖声明</dd><dt>检查记录</dt><dd>{current.security==='待检查'?'暂无记录':'2026-09-05 10:20'}</dd></dl><Button onClick={()=>setNotice('尚未连接安全检查服务，保留最近检查记录。')}>重新检查</Button></section>:view==='edit'?<form style={stack} onSubmit={event=>{event.preventDefault();if(!text.trim()){setNotice('使用说明不能为空。');return;}patch(current.id,{body:text,security:'待检查'});setView('content');setNotice('使用说明已保存，安检状态已重置为待检查。');}}><Field label="SKILL.md"><Textarea aria-label="技能使用说明" value={text} onChange={event=>setText(event.target.value)} minHeight={260}/></Field><div className="cs-resource-page-toolbar"><Button type="button" onClick={()=>setView('content')}>取消编辑</Button><Button type="submit">保存内容</Button></div></form>:<div style={{display:'grid',gridTemplateColumns:'minmax(120px, 1fr) minmax(0, 4fr)',gap:'var(--cs-space-4)'}}><aside aria-label="技能文件"><GroupHeading label="文件"/><Button variant="ghost" onClick={()=>setView('content')}>{current.source==='external'?'包含的技能':'SKILL.md'}</Button></aside><article><p>{current.description}</p><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere',font:'var(--cs-type-body)',margin:0}}>{current.body}</pre>{current.source==='external'&&<p>此工具包的技能文件只读。</p>}</article></div>}
      </>:<EmptyState title="技能不存在" reason="该技能可能已移除，请返回列表重新选择。" action="返回技能" onAction={()=>open(null)}/>:<>
        <window.ResourceToolbar leading={<SegmentedControl ariaLabel="技能分类" items={['全部','通用','文档处理','数据分析']} value={['全部','通用','文档处理','数据分析'].indexOf(category)} onChange={index=>setCategory(['全部','通用','文档处理','数据分析'][index])}/>} search={<Input size="md" aria-label="搜索技能" icon="search" placeholder="搜索技能名称或简介" value={query} onChange={event=>setQuery(event.target.value)}/>} actions={<><Button onClick={showCreate}>创建技能</Button><Button onClick={()=>{setQuery('');setCategory('全部');open('market');}}>更多</Button></>}/>
        <div className="cs-resource-page-toolbar" aria-label="技能安检汇总"><span>安检 · {count('通过')} 项通过 · {count('待检查')} 项待检查 · {count('阻止使用')} 项阻止使用</span><Button variant="ghost" onClick={()=>{const item=trusted.find(item=>item.security==='阻止使用')||trusted[0];if(item)open(item.id,'security');}}>查看安检详情</Button></div>
        {visible.length?Object.entries(sources).map(([source,label])=>{const list=visible.filter(item=>item.source===source);if(!list.length)return null;return <section key={source} style={stack} aria-label={`${label}技能`}><GroupHeading label={`${label} · ${list.length}`}/>{source==='global'?<><ResourceCard title="report" description={`${list.length} 项报告技能`} action={expanded?'收起技能':'展开技能'} onAction={()=>setExpanded(old=>!old)} menu={{groups:[{items:[{label:'启用全部',onSelect:()=>setItems(old=>old.map(item=>item.source==='global'?{...item,enabled:true}:item))},{label:'停用全部',onSelect:()=>setItems(old=>old.map(item=>item.source==='global'?{...item,enabled:false}:item))}]}]}}/>{expanded&&<CardGrid>{list.map(card)}</CardGrid>}</>:<CardGrid>{list.map(card)}</CardGrid>}</section>}):<EmptyState title="没有匹配的技能" action="清除筛选" onAction={()=>{setQuery('');setCategory('全部');}}/>}
      </>}
      {modal?.kind==='delete'&&<Dialog title={`删除「${modal.item.name}」？`} description="技能文件将删除，已有任务与产物保留。此操作不可撤销。" confirmLabel="删除技能" danger onCancel={()=>setModal(null)} onConfirm={()=>{setItems(old=>old.filter(item=>item.id!==modal.item.id));if(selected===modal.item.id)open(null);setModal(null);setNotice('技能已删除');}}/>}
      {modal?.kind==='create'&&<Dialog title="创建技能？" width={520} confirmLabel={method===0?'创建技能':'导入技能'} onCancel={()=>setModal(null)} onConfirm={saveCreate} extra={<div style={{...stack,width:'100%'}}><Tabs items={['手动创建','链接导入','文件夹导入']} value={method} onChange={value=>{setMethod(value);setError('');}}/>{method===0?<><Field label="名称"><Input aria-label="技能名称" maxLength={60} value={draft.name} onChange={event=>setDraft({...draft,name:event.target.value})}/></Field><Field label="简介"><Textarea aria-label="技能简介" placeholder="描述技能要完成的工作" value={draft.description} onChange={event=>setDraft({...draft,description:event.target.value})}/></Field></>:method===1?<Field label="技能链接"><Input aria-label="技能链接" placeholder="https://" value={draft.url} onChange={event=>setDraft({...draft,url:event.target.value})}/></Field>:<p>选择包含 SKILL.md 的技能文件夹。</p>}{error&&<p role="alert">{error}</p>}</div>}/>}
    </div>;
  }
  window.CapabilitySkills=CapabilitySkills;
})();
