const {Button,Icon,Input,EmptyState,StatusPill,SegmentedControl}=window.CogSeedDesignSystem_f581b5;
const D=window.CognitionData;
function CogStatus({children,tone='idle'}){return <StatusPill className="cg-status" tone={tone==='idle'?'neutral':tone}>{children}</StatusPill>;}
function CogFacts({items}){return <dl className="cg-facts">{items.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>;}
function CogSection({title,aside,children}){return <section className="cg-section"><div className="cg-section-heading"><h3>{title}</h3>{aside}</div>{children}</section>;}
function CogEmpty({title='暂无记录',children}){return <div className="cg-empty"><EmptyState title={title}/>{children}</div>;}
function CogMetric({items}){return <div className="cg-metrics">{items.map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>;}
function CogDeep({label}){return <Button size="sm" disabled title="本轮暂不展开此流程">{label}</Button>;}
function CogDetail({asset,go}){return <article className="cg-detail"><header className="cg-detail-head"><span className="cg-kicker">{D.groups[asset.group]} · v{asset.version}</span><h2>{asset.title}</h2><div className="cg-inline"><CogStatus tone={asset.deep?'success':'idle'}>{asset.deep?'效果已验证':'已确认'}</CogStatus><span>更新于 {asset.updated}</span></div></header><CogSection title="沉淀内容"><p className="cg-content-copy">{asset.content}</p></CogSection><CogSection title="使用边界"><CogFacts items={[["作用范围",asset.scope],["所属空间",asset.space],["适用条件",asset.applicable],["禁止范围",asset.forbidden]]}/></CogSection><CogSection title="来源与证据"><div className="cg-evidence"><Icon name="docLines" size={16}/><div><strong>{asset.source}</strong><span>来源会话 · 已确认写入</span></div></div></CogSection><div className="cg-detail-footer"><Button size="sm" onClick={()=>go('versions',{asset:asset.id})}>版本历史</Button><Button size="sm" onClick={()=>go('proof-detail',{asset:asset.id})}>复用与证明</Button>{asset.group===3&&<CogDeep label="查看技能"/>}</div></article>;}
function CogAssetWorkbench({assets,route,go}){
 const [query,setQuery]=React.useState(''); const category=route.group==null?null:Number(route.group);
 const rows=assets.filter(a=>(category==null||a.group===category)&&[a.title,a.content,a.scope].join(' ').includes(query.trim()));
 const selected=rows.find(a=>a.id===route.asset)||rows[0];
 return <><div className="cg-category-grid">{D.groups.map((label,i)=><Button key={label} className={'cg-category '+(category===i?'is-selected':'')} variant="ghost" aria-pressed={category===i} onClick={()=>{setQuery('');go('assets',{group:i});}}><Icon name={['fileText','check','file','automation'][i]} size={18}/><span>{label}</span><strong>{assets.filter(a=>a.group===i).length}</strong></Button>)}</div><div className="cg-workbench"><aside className="cg-list"><div className="cg-list-search"><Input size="md" icon="search" placeholder="搜索资产名称或内容" aria-label="搜索资产" value={query} onChange={e=>setQuery(e.target.value)}/><div className="cg-list-count"><span>{rows.length} 项资产</span>{category!=null&&<Button size="sm" variant="ghost" onClick={()=>go('assets')}>查看全部</Button>}</div></div>{rows.length?rows.map(a=><Button key={a.id} variant="ghost" className={'cg-list-item '+(selected?.id===a.id?'is-selected':'')} aria-pressed={selected?.id===a.id} onClick={()=>go('assets',{group:category,asset:a.id})}><span className={'cg-dot '+(a.deep?'deep':'')}/><span><strong>{a.title}</strong><small>{a.space} · v{a.version}</small></span><Icon name="chevronRight" size={14}/></Button>):<CogEmpty title="未找到匹配的资产"/>}</aside>{selected?<CogDetail asset={selected} go={go}/>:<CogEmpty title="选择资产查看内容"/>}</div></>;
}
function CogCandidate({candidate,decisions,onDecision}){
 const decision=decisions[candidate.id];return <div className="cg-review-layout"><article className="cg-detail"><header className="cg-detail-head"><span className="cg-kicker">{D.groups[candidate.group]} · 候选</span><h2>{candidate.title}</h2><div className="cg-inline"><CogStatus tone={decision?'idle':'attention'}>{decision||'待确认'}</CogStatus><span>{candidate.time}</span></div></header><CogSection title="候选内容"><p className="cg-content-copy">{candidate.content}</p></CogSection><CogSection title="来源依据"><div className="cg-evidence"><Icon name="docLines" size={16}/><div><strong>{candidate.source}</strong><span>来源会话</span></div></div><blockquote>{candidate.quote}</blockquote></CogSection><CogSection title="建议使用范围"><CogFacts items={[["所属空间",candidate.scope],["生效范围","仅限当前空间"],["写入状态",decision==='已确认'?'已确认':'尚未写入正式资产']]}/></CogSection><div className="cg-detail-footer">{decision?<span role="status">已标记为「{decision}」</span>:<><Button variant="primary" onClick={()=>onDecision(candidate,'已确认')}>确认并限域</Button><Button onClick={()=>onDecision(candidate,'已推迟')}>稍后处理</Button><Button variant="ghost" onClick={()=>onDecision(candidate,'已拒绝')}>拒绝候选</Button></>}</div></article><aside className="cg-review-side"><CogSection title="需要判断"><CogStatus tone={candidate.priority?'attention':'idle'}>{candidate.reason}</CogStatus></CogSection><CogSection title="关联资产">{candidate.related?<p>{candidate.related}</p>:<span className="cg-muted">未发现重复资产</span>}</CogSection><CogSection title="处理结果"><CogFacts items={[["确认并限域","保存为正式资产，限定当前空间使用"],["稍后处理","保留候选，不影响现有资产"],["拒绝候选","记录决定，不写入资产"]]}/></CogSection></aside></div>;
}
function CogSources(){const [expanded,setExpanded]=React.useState(['会话']);return <><CogMetric items={[["来源类型",5],["当前可见",8],["可用",7],["需重新连接",1]]}/><div className="cg-source-list">{D.sources.map(s=><section className="cg-source" key={s.title}><Button variant="ghost" className="cg-source-head" aria-expanded={expanded.includes(s.title)} onClick={()=>setExpanded(v=>v.includes(s.title)?v.filter(x=>x!==s.title):[...v,s.title])}><span className="cg-icon-box"><Icon name={s.icon} size={18}/></span><strong>{s.title}</strong><span className="cg-muted">{s.items.length} 项</span><Icon name={expanded.includes(s.title)?'chevronDown':'chevronRight'} size={15}/></Button>{expanded.includes(s.title)&&<div className="cg-source-body">{s.items.map(([name,time,status])=><div className="cg-record" key={name}><div><strong>{name}</strong><small>最近读取 · {time}</small></div><CogStatus tone={status==='可用'?'idle':'attention'}>{status}</CogStatus>{status!=='可用'&&<CogDeep label="重新连接"/>}</div>)}</div>}</section>)}</div><div className="cg-footnote">来源内容不会直接写入正式资产。</div></>;}
function CogCaptures(){const [filter,setFilter]=React.useState('全部'),[selected,setSelected]=React.useState(null);const rows=D.captures.filter(c=>filter==='全部'||c.status===filter);return <><div className="cg-filters"><SegmentedControl ariaLabel="沉淀活动筛选" items={['全部','待我确认','处理中','已完成','异常'].map(f=>`${f} ${D.captures.filter(c=>f==='全部'||c.status===f).length}`)} value={['全部','待我确认','处理中','已完成','异常'].indexOf(filter)} onChange={i=>setFilter(['全部','待我确认','处理中','已完成','异常'][i])}/></div><div className="cg-flow"><span>会话 / 执行结果</span><Icon name="chevronRight" size={14}/><span>提取候选</span><Icon name="chevronRight" size={14}/><span>你确认</span><Icon name="chevronRight" size={14}/><span>我的资产</span></div><div className="cg-table"><div className="cg-table-head"><span>沉淀活动</span><span>状态</span><span>更新时间</span></div>{rows.map(c=><React.Fragment key={c.title}><Button className="cg-capture-row" variant="ghost" aria-expanded={selected===c.title} onClick={()=>setSelected(selected===c.title?null:c.title)}><strong>{c.title}</strong><CogStatus tone={c.status==='异常'||c.status==='待我确认'?'attention':'idle'}>{c.status}</CogStatus><span className="cg-muted">{c.time}</span></Button>{selected===c.title&&<div className="cg-capture-expanded"><p>{c.result}</p><CogFacts items={[["触发方式","会话结束后的自动沉淀"],["来源",c.title],["处理范围","当前会话与执行依据"]]}/></div>}</React.Fragment>)}</div></>;}
function CogAbout(){const [section,setSection]=React.useState('个人本体');const profiles={'个人本体':[['角色','项目助理'],['工作职责','客户沟通、项目材料收集与调研整理'],['决策边界','不代替审批条线作出项目决定']],'项目助理':[['所属条线','项目业务'],['关注事项','材料完整性、业务事实与客户沟通'],['产出','调研报告、到期清单与材料提醒']],'表达与格式':[['表达偏好','先事实与证据，后判断与建议'],['数字口径','汇总项目金额以万元表示'],['报告格式','中文标题，材料名称保留原文']],'工作边界':[['授权范围','当前工作空间内已授权材料'],['对外沟通','发送前由本人确认'],['未知信息','标记待核实，不补写为事实']]};return <div className="cg-workbench cg-about"><aside className="cg-list"><div className="cg-menu-label">我的信息</div><Button className={'cg-list-item '+(section==='个人本体'?'is-selected':'')} variant="ghost" aria-pressed={section==='个人本体'} onClick={()=>setSection('个人本体')}><Icon name="fileText" size={16}/>个人本体</Button><div className="cg-menu-label">角色模板</div><Button className={'cg-list-item '+(section==='项目助理'?'is-selected':'')} variant="ghost" aria-pressed={section==='项目助理'} onClick={()=>setSection('项目助理')}><Icon name="file" size={16}/>项目助理</Button><div className="cg-menu-label">记忆分组</div>{['表达与格式','工作边界'].map(s=><Button key={s} className={'cg-list-item '+(section===s?'is-selected':'')} variant="ghost" aria-pressed={section===s} onClick={()=>setSection(s)}><Icon name="docLines" size={16}/>{s}</Button>)}</aside><article className="cg-detail"><header className="cg-detail-head"><h2>{section}</h2><div className="cg-inline"><CogStatus>已确认</CogStatus><span>最近更新 · 09-05 10:42</span></div></header><CogSection title="已沉淀信息"><CogFacts items={profiles[section]}/></CogSection><CogSection title="来源"><div className="cg-evidence"><Icon name="docLines" size={16}/><div><strong>项目材料清单核验</strong><span>会话中确认的信息</span></div></div></CogSection><div className="cg-detail-footer"><CogDeep label="编辑原文"/><CogDeep label="管理角色模板"/></div></article></div>;}
function CogVersions({asset}){return <div className="cg-review-layout"><article className="cg-detail"><header className="cg-detail-head"><span className="cg-kicker">{D.groups[asset.group]}</span><h2>{asset.title}</h2></header><CogSection title="版本历史">{Array.from({length:asset.version},(_,i)=>asset.version-i).map((v,i)=><div className="cg-timeline-item" key={v}><span className={'cg-dot '+(!i?'deep':'')}/><div><div className="cg-inline"><strong>v{v}</strong>{!i&&<CogStatus tone="success">当前版本</CogStatus>}<span>09-0{5-i} 10:42</span></div><p>{v===1?'确认候选，建立初始版本':v===2?'补充适用条件与禁止范围':'补充材料引用规则与待核实口径'}</p><small>由本人确认 · {asset.space}</small></div></div>)}</CogSection></article><aside className="cg-review-side"><CogSection title="当前状态"><CogFacts items={[["版本",`v${asset.version}`],["使用状态","正常使用"],["所属空间",asset.space],["可回滚版本",asset.version>1?Array.from({length:asset.version-1},(_,i)=>`v${i+1}`).join('、'):'无历史版本']]}/></CogSection><CogDeep label="回滚版本"/></aside></div>;}
function CogProofDetail({asset}){if(asset.id.startsWith('candidate-'))return <CogEmpty title="该资产尚未被带入任务"/>;return <article className="cg-detail"><header className="cg-detail-head"><span className="cg-kicker">{D.groups[asset.group]} · v{asset.version}</span><h2>{asset.title}</h2><div className="cg-inline"><CogStatus tone={asset.deep?'success':'idle'}>{asset.deep?'效果已验证':'尚未验证效果'}</CogStatus></div></header><CogSection title="使用与证明记录">{(asset.deep?['已带入任务','传递已确认','已记录效果评价']:['已带入任务']).map((s,i)=><div className="cg-timeline-item" key={s}><span className={'cg-dot '+(i===2?'deep':'')}/><div><div className="cg-inline"><strong>{s}</strong><span>09-05 10:{12+i*4}</span></div><p>{['项目材料清单核验','目标会话已收到并正确理解指定资产','已依据任务结果记录效果评价'][i]}</p><small>{asset.space} · v{asset.version}</small></div></div>)}</CogSection><CogFacts items={[["传递证明",asset.deep?'已收到并正确理解':'尚无确认回执'],["效果证明",asset.deep?'效果评价已记录':'尚未验证'],["来源任务","项目材料清单核验"]]}/><div className="cg-detail-footer"><CogDeep label="打开来源任务"/><CogDeep label="查看原始回执"/></div></article>;}
Object.assign(window,{CogStatus,CogFacts,CogSection,CogEmpty,CogMetric,CogDeep,CogAssetWorkbench,CogCandidate,CogSources,CogCaptures,CogAbout,CogVersions,CogProofDetail});
