const {Button,Textarea,Input,Checkbox,SettingsSection} = window.CogSeedDesignSystem_f581b5;
// Source: memory.js import input → review/target selection → merge, and export.
// Parsing here only splits preview text; it does not perform the runtime safety scan.
function MemoryTransfer({mode,value,onChange,onClose}) {
  const [text,setText] = React.useState(''), [rows,setRows] = React.useState(null), [notice,setNotice] = React.useState('');
  const raw = scope => value[scope].map(x => x.text).join('\n\n');
  const parse = () => {setRows(text.split(/\n+/).map(t => t.trim()).filter(Boolean).map((text,i) => ({id:`import-${Date.now()}-${i}`,text,target:'user',keep:true})));setNotice('请确认需要导入的记忆。');};
  const merge = () => {const next={...value,user:[...value.user],shared:[...value.shared]};let count=0;rows.filter(r => r.keep).forEach(r => {if(!next[r.target].some(x => x.text === r.text)){next[r.target].push({id:r.id,text:r.text});count++;}});onChange(next);setRows(null);setText('');setNotice(`已合并 ${count} 条记忆，重复内容已跳过。`);};
  return <SettingsSection title={mode === 'export' ? '导出记忆' : rows ? '审核导入内容 · 2 / 2' : '导入记忆 · 1 / 2'} actions={<Button onClick={onClose}>关闭</Button>}>
    {mode === 'export' ? ['user','shared'].map(scope => <div key={scope}><SettingsRow title={scope === 'user' ? '偏好':'全局共享记忆'} help={`${value[scope].length} 条`}><SettingsActions><Button onClick={async () => {try{await navigator.clipboard.writeText(raw(scope));setNotice('内容已复制。');}catch{setNotice('无法访问剪贴板，请在下方选择并复制内容。');}}}>复制内容</Button><Button onClick={() => setNotice('暂无可定位的文件。')}>定位文件</Button></SettingsActions></SettingsRow><Textarea aria-label={scope === 'user' ? '导出偏好内容':'导出共享记忆内容'} readOnly value={raw(scope)} /></div>) : rows ? <><div className="cs-settings-options">{rows.map((r,i) => <div key={r.id}><Checkbox label={r.text} checked={r.keep} onChange={keep => setRows(old => old.map((x,j) => i === j ? {...x,keep}:x))} /><SettingsChoice label={`第 ${i+1} 条存入位置`} options={['偏好','全局共享记忆']} value={r.target === 'user' ? '偏好':'全局共享记忆'} onChange={target => setRows(old => old.map((x,j) => i === j ? {...x,target:target === '偏好' ? 'user':'shared'}:x))} /></div>)}</div><SettingsActions><Button onClick={() => setRows(null)}>返回编辑</Button><Button variant="primary" disabled={!rows.some(r => r.keep)} onClick={merge}>合并 {rows.filter(r => r.keep).length} 条记忆</Button></SettingsActions></> : <><Textarea aria-label="待导入记忆" placeholder="粘贴需要导入的内容，每行一条" value={text} onChange={e => setText(e.target.value)} /><SettingsRow title="从文件导入"><Input type="file" aria-label="选择记忆文件" accept=".txt,.md" onChange={async e => {const file=e.target.files[0];if(!file)return;if(file.size > 1024*1024){setNotice('请选择 1 MB 以内的文本文件。');return;}try{setText(await file.text());setNotice(`已读取「${file.name}」，尚未导入。`);}catch{setNotice('无法读取文件，请重新选择。');}}} /></SettingsRow><SettingsActions><Button onClick={onClose}>取消导入</Button><Button variant="primary" disabled={!text.trim()} onClick={parse}>解析内容</Button></SettingsActions></>}
    <SettingsFeedback>{notice}</SettingsFeedback>
  </SettingsSection>;
}
window.MemoryTransfer = MemoryTransfer;
