// Local preview only. Structure observed in installed CogSeed workspace.js on 2026-09-05.
// All records are fictional; configuration, revoke and task creation never invoke IPC.
const {PageFrame,PageHeader,PageScroll,PageTabs}=window;
const {Button,Icon,IconButton,Input,Textarea,Select,SegmentedControl,EmptyState,SettingsSection,Dialog,StatusPill,DropdownMenu}=window.CogSeedDesignSystem_f581b5;
const SPACE_ASSET_TYPES=['全部','个人身份与偏好','决策规则与方法','文档模板及项目事实','可复用的技能'];
function SpaceDetailScreen({space,setSpaces,collapsed,onExpand,onBack,onOpenTask}){
  const readTab=()=>Math.max(0,['tasks','artifacts','assets'].indexOf(new URLSearchParams(location.search).get('view')));
  const [tab,setTab]=React.useState(readTab),[settings,setSettings]=React.useState(false),[query,setQuery]=React.useState(''),[filter,setFilter]=React.useState(0),[source,setSource]=React.useState('全部来源任务'),[group,setGroup]=React.useState('按时间分组'),[sort,setSort]=React.useState('最近更新'),[layout,setLayout]=React.useState(0),[file,setFile]=React.useState(null),[confirm,setConfirm]=React.useState(null),[notice,setNotice]=React.useState(''),[revoked,setRevoked]=React.useState(space?.revokedAssets||[]),[deletedFiles,setDeletedFiles]=React.useState(space?.deletedArtifacts||[]);
  const trigger=React.useRef(null);
  React.useEffect(()=>{const restore=()=>{setTab(readTab());setSettings(false);};addEventListener('popstate',restore);return()=>removeEventListener('popstate',restore);},[]);
  if(!space)return <PageFrame><PageHeader title="工作空间"/><EmptyState title="找不到这个工作空间" action="返回工作空间" onAction={onBack}/></PageFrame>;
  const changeTab=i=>{setTab(i);setQuery('');setFilter(0);const url=new URL(location.href);url.searchParams.set('view',['tasks','artifacts','assets'][i]);history.pushState(null,'',url);};
  const tasks=space.tasks||[];
  const artifacts=space.hasPreviewRecords&&tasks.length ? [{name:'项目材料核验报告.md',type:'文档',source:tasks[0][1],date:'今天',size:'24 KB',body:'材料核验结果\n\n已核对营业执照、财务报表与项目申请表。担保说明仍需补充签署日期。'}, {name:'项目材料清单.xlsx',type:'表格',source:tasks[0][1],date:'昨天',size:'38 KB',body:'材料名称 · 核验结果\n营业执照 · 已核对\n财务报表 · 已核对\n担保说明 · 待补充'}] : [];
  const assets=space.hasPreviewRecords&&tasks.length ? [{id:'rule',name:'项目材料核验口径',type:2,body:'核验材料时保留来源和统计时点；缺失材料单独列示，不推断未提供的信息。'},{id:'template',name:'交付后监测复核模板',type:3,body:'按客户概况、预警事项、证据和后续行动组织复核记录。'}] : [];
  const shown=artifacts.filter(a=>!deletedFiles.includes(a.name)&&(filter===0||a.type===['全部','文档','表格','演示文稿','网页'][filter])&&(source==='全部来源任务'||a.source===source)&&(a.name+a.source+'材料核验专员').toLowerCase().includes(query.trim().toLowerCase()));
  if(sort==='名称顺序')shown.sort((a,b)=>a.name.localeCompare(b.name,'zh-CN'));else if(sort==='最早更新')shown.reverse();
  const startTask=()=>{const title='新任务';setSpaces(items=>items.map(s=>s.id===space.id?{...s,tasks:[['idle',title],...s.tasks],count:s.tasks.length+1}:s));onOpenTask({title,spaceId:space.id});};
  return <PageFrame>
    <PageHeader title={space.name} collapsed={collapsed} onExpand={onExpand} leading={<IconButton aria-label="返回工作空间" onClick={onBack}><Icon name="chevronLeft"/></IconButton>} actions={<div className="cs-space-actions"><span ref={trigger}><Button onClick={()=>setSettings(true)}>空间设置</Button></span><Button variant="ink" onClick={startTask}>新建任务</Button></div>}/>
    <div className="cs-space-body"><PageScroll className="cs-resource-page-scroll cs-page-tabs-layout"><div className="cs-resource-page-content">
    <PageTabs ariaLabel="工作空间内容" items={[{label:'任务',count:tasks.length},{label:'产物',count:artifacts.filter(a=>!deletedFiles.includes(a.name)).length},{label:'资产',count:assets.length-revoked.length}]} value={tab} onChange={changeTab}/>
      {notice&&<p role="status">{notice}</p>}
      {tab===0&&<><p className="cs-space-meta">{tasks.length} 个任务 · 按最近更新时间排序</p><div className="cs-space-list">{tasks.map((t,i)=><div className="cs-space-row" key={i}><Icon name="fileText"/><button className="cs-space-open" onClick={()=>onOpenTask({title:t[1],spaceId:space.id})}><strong>{t[1]}</strong><small>项目助理 · {i===0?'今天更新':'昨天更新'}</small></button><Button size="sm" variant="ghost" onClick={()=>setConfirm({title:'将任务移出空间？',description:'任务和产物会保留在最近任务中。',label:'移出空间',action:()=>setSpaces(items=>items.map(s=>s.id===space.id?{...s,tasks:s.tasks.filter((_,n)=>n!==i),count:s.tasks.length-1}:s))})}>移出空间</Button></div>)}</div>{!tasks.length&&<EmptyState title="这个空间还没有任务" reason="新建任务，开始处理这项工作。" action="新建任务" onAction={startTask}/>}</>}
      {tab===1&&<><div className="cs-space-tools"><Input aria-label="搜索产物" placeholder="搜索名称、来源任务或 Agent" value={query} onChange={e=>setQuery(e.target.value)}/><Select aria-label="来源任务" options={['全部来源任务',...new Set(artifacts.map(a=>a.source))]} value={source} onChange={setSource}/><Select aria-label="分组方式" options={['按时间分组','不分组']} value={group} onChange={setGroup}/><Select aria-label="排序方式" options={['最近更新','最早更新','名称顺序']} value={sort} onChange={setSort}/></div><div className="cs-space-toolbar"><SegmentedControl items={['全部','文档','表格','演示文稿','网页'].map((label,i)=>`${label} ${artifacts.filter(a=>!deletedFiles.includes(a.name)&&(!i||a.type===label)).length}`)} value={filter} onChange={setFilter}/><SegmentedControl items={['列表','卡片']} value={layout} onChange={setLayout}/></div><p className="cs-space-meta">共 {shown.length} 个产物</p><div className={layout?'cs-space-file-grid':'cs-space-list'}>{shown.map(a=><article className="cs-space-file" key={a.name}>{group==='按时间分组'&&<small>{a.date}</small>}<div className="cs-space-row"><Icon name="file"/><button className="cs-space-open" onClick={()=>setFile(a)}><strong>{a.name}</strong><small>{a.type} · {a.size} · 材料核验专员</small></button><DropdownMenu align="end" trigger={<IconButton aria-label={`${a.name} · 更多操作`}><Icon name="dots"/></IconButton>} groups={[{items:[{label:'引用到新任务',onSelect:()=>{const title=`引用 ${a.name}`;setSpaces(items=>items.map(s=>s.id===space.id?{...s,tasks:[['idle',title],...s.tasks],count:s.tasks.length+1}:s));onOpenTask({title,spaceId:space.id,reference:a.name});}},{label:'在原任务查看',onSelect:()=>onOpenTask({title:a.source,spaceId:space.id})},{label:'在文件夹显示',disabled:true}]},{danger:true,items:[{label:'删除产物',onSelect:()=>setConfirm({title:'删除这份产物？',description:'该产物将从空间移除，来源任务保留。',label:'删除产物',action:()=>{setDeletedFiles(v=>[...v,a.name]);setSpaces(items=>items.map(s=>s.id===space.id?{...s,deletedArtifacts:[...(s.deletedArtifacts||[]),a.name]}:s));}})}]}]}/></div><Button size="sm" variant="ghost" onClick={()=>onOpenTask({title:a.source,spaceId:space.id})}>来源任务：{a.source}</Button></article>)}</div>{!shown.length&&<EmptyState title="没有匹配的产物" reason="调整筛选条件，或在任务中生成产物。"/>}</>}
      {tab===2&&<><p className="cs-space-meta">资产仅包含四类经过确认、可持续复用的认知与能力。</p><div className="cs-space-toolbar"><SegmentedControl items={SPACE_ASSET_TYPES.map((label,i)=>`${label} ${assets.filter(a=>(!i||a.type===i)&&!revoked.includes(a.id)).length}`)} value={filter} onChange={setFilter}/></div><div className="cs-space-file-grid">{assets.filter(a=>(filter===0||a.type===filter)&&!revoked.includes(a.id)).map(a=><SettingsSection key={a.id} title={a.name} actions={<Button size="sm" variant="ghost" onClick={()=>setConfirm({title:'撤销这项空间资产？',description:'撤销后不再用于后续任务，来源任务保留。',label:'撤销资产',action:()=>{setRevoked(v=>[...v,a.id]);setSpaces(items=>items.map(s=>s.id===space.id?{...s,revokedAssets:[...(s.revokedAssets||[]),a.id]}:s));}})}>撤销资产</Button>}><p>{a.body}</p><small>{SPACE_ASSET_TYPES[a.type]} · 已沉淀 · seed</small><StatusPill>{SPACE_ASSET_TYPES[a.type]}</StatusPill></SettingsSection>)}</div>{!assets.some(a=>(filter===0||a.type===filter)&&!revoked.includes(a.id))&&<EmptyState title="这个分类还没有资产" reason="任务中的认知确认后会沉淀到这里。"/>}</>}
    </div></PageScroll>{settings&&<SpaceSettings space={space} onSave={patch=>{setSpaces(items=>items.map(s=>s.id===space.id?{...s,...patch}:s));setNotice('空间设置已保存。');}} onClose={()=>{setSettings(false);trigger.current?.querySelector('button')?.focus();}}/>}</div>
    {file&&<Dialog title={file.name} description={file.body} cancelLabel="关闭" confirmLabel="查看来源任务" onCancel={()=>setFile(null)} onConfirm={()=>{setFile(null);onOpenTask({title:file.source,spaceId:space.id});}}/>}
    {confirm&&<Dialog title={confirm.title} description={confirm.description} confirmLabel={confirm.label} onCancel={()=>setConfirm(null)} onConfirm={()=>{confirm.action();setConfirm(null);setNotice('操作已完成。');}}/>}
  </PageFrame>;
}
function SpaceSettings({space,onSave,onClose}){
  const {SpaceCapabilityRows,spaceConfig,spaceEffective}=window;
  const [instructions,setInstructions]=React.useState(space.instructions||''),[saved,setSaved]=React.useState(false),[mainPicker,setMainPicker]=React.useState(false),[main,setMain]=React.useState(space.main||'未设置');const panel=React.useRef(null);
  React.useEffect(()=>{panel.current?.focus();},[]);
  const config=spaceConfig(space);
  return <aside className="cs-space-settings" aria-label="空间设置" tabIndex={-1} ref={panel} onKeyDown={e=>{if(e.key==='Escape'&&!e.defaultPrevented&&!e.isComposing&&e.keyCode!==229){e.preventDefault();onClose();}}}>
    <div className="cs-space-setting-head"><strong>空间设置</strong><IconButton aria-label="关闭空间设置" onClick={onClose}><Icon name="close"/></IconButton></div>
    <div className="cs-space-setting-content"><SettingsSection title="默认目标 / 指令"><Textarea aria-label="默认目标或指令" rows={5} maxLength={4000} value={instructions} onChange={e=>{setInstructions(e.target.value);setSaved(false);}}/><Button onClick={()=>{onSave({instructions});setSaved(true);}}>保存</Button>{saved&&<p role="status">指令已保存</p>}<p className="cs-space-meta">配置更新后，从下一次交互开始生效。</p></SettingsSection>
    <SettingsSection title="能力配置"><SpaceCapabilityRows config={config} includeAgents onChange={value=>onSave({agents:value.agents,roles:value.roles,taskAgents:value.taskAgents,skills:value.skills})}/></SettingsSection>
    <SettingsSection title="主 Skill"><div className="cs-space-capability"><span>{space.main||'未设置'}</span><Button onClick={()=>{setMain(space.main||'未设置');setMainPicker(true);}}>选择</Button></div></SettingsSection>
    <SettingsSection title="失效引用"><span className="cs-space-meta">{space.invalidRefs?.length?`${space.invalidRefs.length} 项 · ${space.invalidRefs.join('、')}`:'无失效引用'}</span>{space.invalidRefs?.length>0&&<Button onClick={()=>onSave({invalidRefs:[]})}>清理</Button>}</SettingsSection>
    </div>{mainPicker&&<Dialog title="选择主 Skill" description="主 Skill 作为空间的核心能力入口（可选）。" cancelLabel="取消" confirmLabel="保存选择" onCancel={()=>setMainPicker(false)} onConfirm={()=>{onSave({main});setMainPicker(false);}} extra={<Select aria-label="主 Skill" options={['未设置',...spaceEffective(config,'skills')]} value={main} onChange={setMain}/>}/>}</aside>;
}
window.SpaceDetailScreen=SpaceDetailScreen;
