// Space workflow composition shared by center and detail settings. Fictional catalogs only;
// directory picker retains the chosen directory name, never scans file contents or grants IPC access.
const { PageFrame, PageHeader, PageScroll, PreviewNameEditor } = window;
const { InlineConfirm, ResourceCard, CardGrid, GroupHeading, EmptyState, Button, Input, Textarea, Select, Dialog, Checkbox, SettingsSection } = window.CogSeedDesignSystem_f581b5;
const SPACE_CATALOG={roles:['产品经理','软件工程师','项目分析师','质量复核员'],agents:['cogseed','Codex','Claude Code'],taskAgents:['材料核验专员','风险复核专员','文档整理专员'],skills:['材料核验','风险复核','整理文档']};
const ROLE_BUNDLES={'产品经理':{taskAgents:['文档整理专员'],skills:['整理文档']},'软件工程师':{taskAgents:[],skills:[]},'项目分析师':{taskAgents:['材料核验专员'],skills:['材料核验']},'质量复核员':{taskAgents:['风险复核专员'],skills:['风险复核']}};
const SPACE_LABELS={roles:'角色',agents:'当前对话 Agent',taskAgents:'Task Agent',skills:'Skill'};
function spaceConfig(space={}){return {...space,roles:space.roles||[],agents:space.agents||['cogseed'],taskAgents:space.taskAgents||[],skills:space.skills||[],instructions:space.instructions||'',main:space.main||'未设置'};}
function spaceEffective(config,key){return [...new Set([...(config[key]||[]),...(config.roles||[]).flatMap(r=>ROLE_BUNDLES[r]?.[key]||[])])];}
function SpaceAbilityPicker({kind,config,onSave,onCancel}){
 const [draft,setDraft]=React.useState(()=>spaceConfig(config)),[query,setQuery]=React.useState(''),[active,setActive]=React.useState(kind);
 const keys=kind==='agents'?['agents']:['roles','taskAgents','skills'];
 const bundled=active==='roles'||active==='agents'?[]:(draft.roles||[]).flatMap(r=>ROLE_BUNDLES[r]?.[active]||[]);
 return <Dialog title={kind==='agents'?'调整当前对话 Agent':'调整空间能力'} width={640} cancelLabel="取消" confirmLabel="保存选择" onCancel={onCancel} onConfirm={()=>onSave(draft)} extra={<div className="cs-space-form"><div className="cs-space-actions">{keys.map(k=><Button key={k} aria-pressed={active===k} onClick={()=>{setActive(k);setQuery('');}}>{SPACE_LABELS[k]}</Button>)}</div><Input aria-label="搜索空间能力" placeholder="搜索名称" value={query} onChange={e=>setQuery(e.target.value)}/>{active==='skills'&&<p className="cs-space-meta">Skill：模板内置项固定开启，额外勾选的内容会写入空间扩充配置。</p>}{active==='roles'&&<p className="cs-space-meta">最多选择 3 个角色模板（1 主 + 2 副），首个作为主角色。</p>}<div className="cs-space-options">{SPACE_CATALOG[active].filter(n=>n.toLowerCase().includes(query.trim().toLowerCase())).map(n=><Checkbox key={n} label={n} help={bundled.includes(n)?'模板内置':active==='roles'&&draft.roles[0]===n?'主角色':undefined} checked={spaceEffective(draft,active).includes(n)} disabled={bundled.includes(n)||active==='roles'&&!draft.roles.includes(n)&&draft.roles.length>=3} onChange={checked=>setDraft(d=>({...d,[active]:checked?[...d[active],n]:d[active].filter(v=>v!==n)}))}/>)}</div>{!SPACE_CATALOG[active].some(n=>n.toLowerCase().includes(query.trim().toLowerCase()))&&<EmptyState title="没有匹配的能力"/>}</div>}/>;
}
function SpaceCapabilityRows({config,onChange,includeAgents=false}){
 const [picker,setPicker]=React.useState(null);
 return <>{(includeAgents?['agents','roles','taskAgents','skills']:['roles','taskAgents','skills']).map(k=><div className="cs-space-capability" key={k}><div><strong>{SPACE_LABELS[k]} · {spaceEffective(config,k).length}</strong><p className="cs-space-meta">{spaceEffective(config,k).map((n,i)=>k==='roles'&&i===0?`主 · ${n}`:n).join('、')||'未选择'}</p></div><Button size="sm" onClick={()=>setPicker(k)}>调整</Button></div>)}{picker&&<SpaceAbilityPicker kind={picker} config={config} onCancel={()=>setPicker(null)} onSave={value=>{onChange(value);setPicker(null);}}/>}</>;
}
function SpaceCreateDialog({initial={},onCancel,onCreate}){
 const [draft,setDraft]=React.useState(()=>spaceConfig(initial)),[error,setError]=React.useState('');const folder=React.useRef(null);
 return <Dialog title="新建空间" width={680} cancelLabel="取消" confirmLabel="创建空间" onCancel={onCancel} onConfirm={()=>{if(!draft.name?.trim()){setError('请填写空间名称。');return;}onCreate({...draft,name:draft.name.trim()});}} extra={<div className="cs-space-form"><label className="cs-space-setting-field">空间名称<Input aria-label="空间名称" aria-invalid={!!error} aria-describedby={error?'space-name-error':undefined} maxLength={60} value={draft.name||''} onChange={e=>{setDraft({...draft,name:e.target.value});setError('');}}/></label>{error&&<p id="space-name-error" role="alert">{error}</p>}<SettingsSection title="本地文件夹（选填）"><div className="cs-space-capability"><span>{draft.directory||'未选择——空间创建后为空'}</span><Button onClick={()=>folder.current?.click()}>选择文件夹</Button>{draft.directory&&<Button onClick={()=>setDraft({...draft,directory:''})}>移除</Button>}</div><input ref={folder} type="file" webkitdirectory="" hidden onChange={e=>{const first=e.target.files?.[0];if(first)setDraft({...draft,directory:first.webkitRelativePath.split('/')[0]});}}/></SettingsSection><SettingsSection title="可协作 AI 工具 Agent"><div className="cs-space-options">{SPACE_CATALOG.agents.map(n=><Checkbox key={n} label={n} checked={draft.agents.includes(n)} disabled={n==='cogseed'} onChange={v=>setDraft({...draft,agents:v?[...draft.agents,n]:draft.agents.filter(a=>a!==n)})}/>)}</div><p className="cs-space-meta">任务中可通过 @ 明确调用</p></SettingsSection><label className="cs-space-setting-field">默认目标/指令<Textarea aria-label="默认目标/指令" maxLength={500} rows={4} placeholder="填写空间的背景、目标、工作方式、输出要求等" value={draft.instructions} onChange={e=>setDraft({...draft,instructions:e.target.value})}/><small>{draft.instructions.length} / 500</small></label><SettingsSection title="能力配置"><p className="cs-space-meta">角色、Task Agent 与 Skill 均为可选，可按需添加。</p><SpaceCapabilityRows config={draft} onChange={setDraft}/></SettingsSection><p className="cs-space-meta">创建后将自动进入空间的第一个新任务。</p></div>}/>;
}
function SpaceHubScreen({spaces,setSpaces,collapsed,onExpand,onOpenTask,onOpenSpace}){
 const [query,setQuery]=React.useState(''),[sort,setSort]=React.useState('最近使用'),[editor,setEditor]=React.useState(null),[creating,setCreating]=React.useState(null),[deleting,setDeleting]=React.useState(null),[notice,setNotice]=React.useState('');
 const visible=spaces.filter(s=>`${s.name} ${s.sub||''}`.toLowerCase().includes(query.trim().toLowerCase())).sort((a,b)=>sort==='按名称'?a.name.localeCompare(b.name,'zh-CN'):(b.updatedAt||0)-(a.updatedAt||0));
 const update=(id,patch)=>setSpaces(items=>items.map(s=>s.id===id?{...s,...patch}:s));
 const resume=s=>{const title=s.tasks?.[0]?.[1]||'新任务';update(s.id,{updatedAt:Date.now(),...(!s.tasks?.length?{tasks:[['idle',title]],count:1}:{})});onOpenTask({title,spaceId:s.id});};
 const templates=SPACE_CATALOG.roles.map((name,i)=>({name,sub:['梳理产品需求、组织资料与推进评审。','分析代码、实现功能与验证结果。','核验项目材料并整理风险线索。','复核风险事项并保留依据。'][i],roles:[name]}));
 return <PageFrame><PageHeader title="工作空间" collapsed={collapsed} onExpand={onExpand} actions={<Button onClick={()=>setCreating({})}>新建空间</Button>}/><PageScroll className="cs-resource-page-scroll"><div className="cs-resource-page-content"><window.ResourceToolbar leading={<GroupHeading label={`我的空间 · ${spaces.length}`}/>} search={<Input size="md" icon="search" aria-label="搜索已创建的空间" placeholder="搜索已创建的空间" value={query} onChange={e=>setQuery(e.target.value)}/>} actions={<Select size="md" aria-label="空间排序" options={['最近使用','按名称']} value={sort} onChange={setSort}/>}/>{notice&&<p role="status">{notice}</p>}
 {editor&&<PreviewNameEditor title="重命名空间" initial={editor.name} onCancel={()=>setEditor(null)} onSave={name=>{update(editor.id,{name});setEditor(null);}}/>}
 {deleting&&<InlineConfirm title={`删除「${deleting.name}」？`} description="空间将从列表移除，任务和产物保留。" confirmLabel="删除空间" onCancel={()=>setDeleting(null)} onConfirm={()=>{setSpaces(items=>items.filter(s=>s.id!==deleting.id));setDeleting(null);setNotice('工作空间已删除。');}}/>}
 {visible.length?<CardGrid>{visible.map((s,i)=><ResourceCard key={s.id} variant="workspace" icon={s.icon||'space'} title={s.name} description={s.instructions||s.sub} workspace={{updatedAt:s.updatedAt?(Date.now()-s.updatedAt<60000?'刚刚更新':new Date(s.updatedAt).toLocaleDateString('zh-CN')+' 更新'):'暂无更新',roles:s.roles||[],recentTask:s.tasks?.[0]?.[1]}} onOpen={()=>onOpenSpace(s)} action="继续工作" onAction={()=>resume(s)} menu={{details:[{label:'类型',value:'工作空间'},{label:'角色模板',value:s.roles?.join('、')||'未设置'},{label:'Skill',value:`${spaceEffective(spaceConfig(s),'skills').length} 项`},{label:'Agent',value:`${spaceEffective(spaceConfig(s),'taskAgents').length} 个`}],groups:[{items:[{label:'重命名',onSelect:()=>setEditor(s)}]},{danger:true,items:[{label:'删除空间',onSelect:()=>setDeleting(s)}]}]}}/>)}</CardGrid>:<EmptyState title={spaces.length?'没有匹配的空间':'还没有工作空间'} reason="点击新建空间，或从下方模板开始。" action={spaces.length?'清除搜索':'新建空间'} onAction={()=>spaces.length?setQuery(''):setCreating({})}/>}
 <section className="cs-resource-page-section"><GroupHeading label="从模板创建"/><h3 className="cs-space-meta">场景</h3><CardGrid>{[{name:'职场',sub:'组织日常工作与交付。',roles:['产品经理']},{name:'软件开发',sub:'从需求到实现，接续项目工作。',roles:['软件工程师','产品经理']},{name:'自定义',sub:'按自己的工作方式配置空间。',roles:[]}].map(t=><ResourceCard key={t.name} variant="template" title={t.name} description={t.sub} status={t.roles.join(' + ')||'自定义配置'} action="用此场景创建" onAction={()=>setCreating({...t,instructions:t.sub})}/>)}</CardGrid><h3 className="cs-space-meta">角色模板</h3><CardGrid>{templates.map(t=><ResourceCard key={t.name} variant="template" title={t.name} description={t.sub} status={`${ROLE_BUNDLES[t.name].skills.length} 个 Skill · ${ROLE_BUNDLES[t.name].taskAgents.length} 个 Agent`} action="用此模板创建" onAction={()=>setCreating({...t,instructions:t.sub})}/>)}</CardGrid></section>
 </div></PageScroll>{creating&&<SpaceCreateDialog initial={creating} onCancel={()=>setCreating(null)} onCreate={value=>{const s={...value,id:`space-${Date.now()}`,sub:value.instructions,icon:'space',tasks:[['idle','新任务']],count:1,owned:true,updatedAt:Date.now()};setSpaces(items=>[s,...items]);setCreating(null);onOpenTask({title:'新任务',spaceId:s.id});}}/>}</PageFrame>;
}
Object.assign(window,{SpaceHubScreen,SpaceAbilityPicker,SpaceCapabilityRows,spaceConfig,spaceEffective});
