/* Generated from components/actions/buttons.card.demo.jsx by tools/build.cjs. */
(() => {
  const { Button, IconButton, Icon } = window.CogSeedDesignSystem_f581b5;
  function Demo() {
    const [busy, setBusy] = React.useState(false);
    React.useEffect(() => {
      if (!busy) return;
      const timer = setTimeout(() => setBusy(false), 1200);
      return () => clearTimeout(timer);
    }, [busy]);
    return /* @__PURE__ */ React.createElement("div", { className: "cs-col", style: { gap: "var(--cs-space-3)" } }, /* @__PURE__ */ React.createElement("div", { className: "cs-row" }, /* @__PURE__ */ React.createElement(Button, { variant: "primary", icon: /* @__PURE__ */ React.createElement(Icon, { name: "plus", size: 14 }) }, "\u65B0\u5EFA\u7A7A\u95F4"), /* @__PURE__ */ React.createElement(Button, null, "\u6B21\u64CD\u4F5C"), /* @__PURE__ */ React.createElement(Button, { variant: "suggestion" }, "\u9879\u76EE\u6750\u6599\u6838\u5BF9"), /* @__PURE__ */ React.createElement(Button, { variant: "ghost" }, "\u6587\u5B57\u6309\u94AE"), /* @__PURE__ */ React.createElement(Button, { variant: "danger" }, "\u5371\u9669\u64CD\u4F5C"), /* @__PURE__ */ React.createElement(Button, { disabled: true }, "\u7981\u7528"), /* @__PURE__ */ React.createElement(Button, { variant: "primary", loading: busy, onClick: () => setBusy(true) }, "\u63D0\u4EA4\u6750\u6599")), /* @__PURE__ */ React.createElement("div", { className: "cs-row" }, /* @__PURE__ */ React.createElement(Button, { variant: "primary", size: "login" }, "\u767B\u5F55"), /* @__PURE__ */ React.createElement(Button, { size: "sm" }, "28 sm"), /* @__PURE__ */ React.createElement(Button, { size: "md" }, "32 md"), /* @__PURE__ */ React.createElement(Button, { size: "lg" }, "36 lg"), /* @__PURE__ */ React.createElement("span", { style: { width: 1, height: 18, background: "var(--cs-border-field)" } }), /* @__PURE__ */ React.createElement(IconButton, { size: "sm", variant: "quiet" }, /* @__PURE__ */ React.createElement(Icon, { name: "plus", size: 15 })), /* @__PURE__ */ React.createElement(IconButton, null, /* @__PURE__ */ React.createElement(Icon, { name: "plus", size: 14 })), /* @__PURE__ */ React.createElement(IconButton, { variant: "accent" }, /* @__PURE__ */ React.createElement(Icon, { name: "send", size: 15 })), /* @__PURE__ */ React.createElement(IconButton, { disabled: true }, /* @__PURE__ */ React.createElement(Icon, { name: "send", size: 15 })), /* @__PURE__ */ React.createElement(Button, { variant: "ink" }, "\u5141\u8BB8\u4E00\u6B21"), /* @__PURE__ */ React.createElement(Button, { variant: "dangerSolid" }, "\u5220\u9664")), /* @__PURE__ */ React.createElement("div", { style: { fontSize: "var(--cs-size-caption)", color: "var(--cs-ink-45)" } }, "\u4E1A\u52A1\u9875\u9762\u4E00\u5C4F\u6700\u591A\u4E00\u4E2A\u4E3B\u8981\u64CD\u4F5C\u6309\u94AE\uFF1B\u8FD9\u91CC\u5E76\u5217\u5C55\u793A\u4E0D\u540C\u7EC4\u4EF6\u72B6\u6001\u3002Tab \u68C0\u67E5\u7126\u70B9\uFF0C\u70B9\u51FB\u63D0\u4EA4\u6750\u6599\u68C0\u67E5\u52A0\u8F7D\u72B6\u6001\u3002"));
  }
  ReactDOM.createRoot(document.getElementById("root")).render(/* @__PURE__ */ React.createElement(Demo, null));
})();
